/*
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSiddhiScopeProvider extends DelegatingScopeProvider {
}
