/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.siddhi;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>AGGREGATE</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.siddhi.siddhi.AGGREGATE#getAgrregate <em>Agrregate</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getAGGREGATE()
 * @model
 * @generated
 */
public interface AGGREGATE extends EObject
{
  /**
   * Returns the value of the '<em><b>Agrregate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Agrregate</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Agrregate</em>' attribute.
   * @see #setAgrregate(String)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getAGGREGATE_Agrregate()
   * @model
   * @generated
   */
  String getAgrregate();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.AGGREGATE#getAgrregate <em>Agrregate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Agrregate</em>' attribute.
   * @see #getAgrregate()
   * @generated
   */
  void setAgrregate(String value);

} // AGGREGATE
