/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.siddhi;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Aggregation Time Range</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getAggregationTimeRange()
 * @model
 * @generated
 */
public interface AggregationTimeRange extends AggregationTime
{
} // AggregationTimeRange
