/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.siddhi;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>APP</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.siddhi.siddhi.APP#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.APP#getAnn5 <em>Ann5</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.APP#getAp <em>Ap</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getAPP()
 * @model
 * @generated
 */
public interface APP extends AppAnnotation
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' containment reference.
   * @see #setName(Name)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getAPP_Name()
   * @model containment="true"
   * @generated
   */
  Name getName();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.APP#getName <em>Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' containment reference.
   * @see #getName()
   * @generated
   */
  void setName(Name value);

  /**
   * Returns the value of the '<em><b>Ann5</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.siddhi.siddhi.AnnotationElement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ann5</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ann5</em>' containment reference list.
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getAPP_Ann5()
   * @model containment="true"
   * @generated
   */
  EList<AnnotationElement> getAnn5();

  /**
   * Returns the value of the '<em><b>Ap</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ap</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ap</em>' attribute.
   * @see #setAp(String)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getAPP_Ap()
   * @model
   * @generated
   */
  String getAp();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.APP#getAp <em>Ap</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ap</em>' attribute.
   * @see #getAp()
   * @generated
   */
  void setAp(String value);

} // APP
