/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.siddhi;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Attribute Index</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getAttributeIndex()
 * @model
 * @generated
 */
public interface AttributeIndex extends LAST
{
} // AttributeIndex
