/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.siddhi;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Basic Source Stream Handlers1</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.siddhi.siddhi.BasicSourceStreamHandlers1#getExp <em>Exp</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.BasicSourceStreamHandlers1#getFo <em>Fo</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.BasicSourceStreamHandlers1#getFunc_op <em>Func op</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getBasicSourceStreamHandlers1()
 * @model
 * @generated
 */
public interface BasicSourceStreamHandlers1 extends WINDOW
{
  /**
   * Returns the value of the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exp</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp</em>' containment reference.
   * @see #setExp(Expression)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getBasicSourceStreamHandlers1_Exp()
   * @model containment="true"
   * @generated
   */
  Expression getExp();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.BasicSourceStreamHandlers1#getExp <em>Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp</em>' containment reference.
   * @see #getExp()
   * @generated
   */
  void setExp(Expression value);

  /**
   * Returns the value of the '<em><b>Fo</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fo</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fo</em>' containment reference.
   * @see #setFo(FunctionOperation)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getBasicSourceStreamHandlers1_Fo()
   * @model containment="true"
   * @generated
   */
  FunctionOperation getFo();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.BasicSourceStreamHandlers1#getFo <em>Fo</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fo</em>' containment reference.
   * @see #getFo()
   * @generated
   */
  void setFo(FunctionOperation value);

  /**
   * Returns the value of the '<em><b>Func op</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Func op</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Func op</em>' containment reference.
   * @see #setFunc_op(FunctionOperation)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getBasicSourceStreamHandlers1_Func_op()
   * @model containment="true"
   * @generated
   */
  FunctionOperation getFunc_op();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.BasicSourceStreamHandlers1#getFunc_op <em>Func op</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Func op</em>' containment reference.
   * @see #getFunc_op()
   * @generated
   */
  void setFunc_op(FunctionOperation value);

} // BasicSourceStreamHandlers1
