/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.siddhi;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>For Time</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.siddhi.siddhi.ForTime#getTv <em>Tv</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getForTime()
 * @model
 * @generated
 */
public interface ForTime extends FOR
{
  /**
   * Returns the value of the '<em><b>Tv</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tv</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tv</em>' containment reference.
   * @see #setTv(TimeValue)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getForTime_Tv()
   * @model containment="true"
   * @generated
   */
  TimeValue getTv();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.ForTime#getTv <em>Tv</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tv</em>' containment reference.
   * @see #getTv()
   * @generated
   */
  void setTv(TimeValue value);

} // ForTime
