/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.siddhi;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>FULL</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.siddhi.siddhi.FULL#getFull <em>Full</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getFULL()
 * @model
 * @generated
 */
public interface FULL extends EObject
{
  /**
   * Returns the value of the '<em><b>Full</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Full</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Full</em>' attribute.
   * @see #setFull(String)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getFULL_Full()
   * @model
   * @generated
   */
  String getFull();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.FULL#getFull <em>Full</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Full</em>' attribute.
   * @see #getFull()
   * @generated
   */
  void setFull(String value);

} // FULL
