/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.siddhi;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>HOURS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.siddhi.siddhi.HOURS#getHour <em>Hour</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.HOURS#getHours <em>Hours</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getHOURS()
 * @model
 * @generated
 */
public interface HOURS extends EObject
{
  /**
   * Returns the value of the '<em><b>Hour</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Hour</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hour</em>' attribute.
   * @see #setHour(String)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getHOURS_Hour()
   * @model
   * @generated
   */
  String getHour();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.HOURS#getHour <em>Hour</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Hour</em>' attribute.
   * @see #getHour()
   * @generated
   */
  void setHour(String value);

  /**
   * Returns the value of the '<em><b>Hours</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Hours</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hours</em>' attribute.
   * @see #setHours(String)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getHOURS_Hours()
   * @model
   * @generated
   */
  String getHours();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.HOURS#getHours <em>Hours</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Hours</em>' attribute.
   * @see #getHours()
   * @generated
   */
  void setHours(String value);

} // HOURS
