/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.siddhi;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>joins</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getjoins()
 * @model
 * @generated
 */
public interface joins extends LEFT, OUTER, JOIN, RIGHT, FULL, INNER
{
} // joins
