/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.siddhi;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>LAST</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.siddhi.siddhi.LAST#getLast <em>Last</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getLAST()
 * @model
 * @generated
 */
public interface LAST extends EObject
{
  /**
   * Returns the value of the '<em><b>Last</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Last</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Last</em>' attribute.
   * @see #setLast(String)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getLAST_Last()
   * @model
   * @generated
   */
  String getLast();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.LAST#getLast <em>Last</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Last</em>' attribute.
   * @see #getLast()
   * @generated
   */
  void setLast(String value);

} // LAST
