/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.siddhi;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Left Absent Sequence Source1</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getLeftAbsentSequenceSource1()
 * @model
 * @generated
 */
public interface LeftAbsentSequenceSource1 extends LeftAbsentSequenceSource
{
} // LeftAbsentSequenceSource1
