/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.siddhi;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Math Addsub Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.siddhi.siddhi.MathAddsubOperation#getLeft <em>Left</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.MathAddsubOperation#getAdd <em>Add</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.MathAddsubOperation#getSubstract <em>Substract</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.MathAddsubOperation#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getMathAddsubOperation()
 * @model
 * @generated
 */
public interface MathAddsubOperation extends MathOperation
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Left</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(MathOperation)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getMathAddsubOperation_Left()
   * @model containment="true"
   * @generated
   */
  MathOperation getLeft();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.MathAddsubOperation#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(MathOperation value);

  /**
   * Returns the value of the '<em><b>Add</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Add</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Add</em>' attribute.
   * @see #setAdd(String)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getMathAddsubOperation_Add()
   * @model
   * @generated
   */
  String getAdd();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.MathAddsubOperation#getAdd <em>Add</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Add</em>' attribute.
   * @see #getAdd()
   * @generated
   */
  void setAdd(String value);

  /**
   * Returns the value of the '<em><b>Substract</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Substract</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Substract</em>' attribute.
   * @see #setSubstract(String)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getMathAddsubOperation_Substract()
   * @model
   * @generated
   */
  String getSubstract();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.MathAddsubOperation#getSubstract <em>Substract</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Substract</em>' attribute.
   * @see #getSubstract()
   * @generated
   */
  void setSubstract(String value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Right</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(MathOperation)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getMathAddsubOperation_Right()
   * @model containment="true"
   * @generated
   */
  MathOperation getRight();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.MathAddsubOperation#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(MathOperation value);

} // MathAddsubOperation
