/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.siddhi;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>MONTHS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.siddhi.siddhi.MONTHS#getMonth <em>Month</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.MONTHS#getMonths <em>Months</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getMONTHS()
 * @model
 * @generated
 */
public interface MONTHS extends EObject
{
  /**
   * Returns the value of the '<em><b>Month</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Month</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Month</em>' attribute.
   * @see #setMonth(String)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getMONTHS_Month()
   * @model
   * @generated
   */
  String getMonth();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.MONTHS#getMonth <em>Month</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Month</em>' attribute.
   * @see #getMonth()
   * @generated
   */
  void setMonth(String value);

  /**
   * Returns the value of the '<em><b>Months</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Months</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Months</em>' attribute.
   * @see #setMonths(String)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getMONTHS_Months()
   * @model
   * @generated
   */
  String getMonths();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.MONTHS#getMonths <em>Months</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Months</em>' attribute.
   * @see #getMonths()
   * @generated
   */
  void setMonths(String value);

} // MONTHS
