/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.siddhi;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>NOT</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.siddhi.siddhi.NOT#getBasicSrc <em>Basic Src</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.NOT#getFt <em>Ft</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.NOT#getNot1 <em>Not1</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getNOT()
 * @model
 * @generated
 */
public interface NOT extends LogicalAbsentStatefulSource, BasicAbsentPatternSource
{
  /**
   * Returns the value of the '<em><b>Basic Src</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Basic Src</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Basic Src</em>' containment reference.
   * @see #setBasicSrc(BasicSource)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getNOT_BasicSrc()
   * @model containment="true"
   * @generated
   */
  BasicSource getBasicSrc();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.NOT#getBasicSrc <em>Basic Src</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Basic Src</em>' containment reference.
   * @see #getBasicSrc()
   * @generated
   */
  void setBasicSrc(BasicSource value);

  /**
   * Returns the value of the '<em><b>Ft</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ft</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ft</em>' containment reference.
   * @see #setFt(ForTime)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getNOT_Ft()
   * @model containment="true"
   * @generated
   */
  ForTime getFt();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.NOT#getFt <em>Ft</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ft</em>' containment reference.
   * @see #getFt()
   * @generated
   */
  void setFt(ForTime value);

  /**
   * Returns the value of the '<em><b>Not1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Not1</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Not1</em>' attribute.
   * @see #setNot1(String)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getNOT_Not1()
   * @model
   * @generated
   */
  String getNot1();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.NOT#getNot1 <em>Not1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Not1</em>' attribute.
   * @see #getNot1()
   * @generated
   */
  void setNot1(String value);

} // NOT
