/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.siddhi;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Output Event Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getOutputEventType()
 * @model
 * @generated
 */
public interface OutputEventType extends ALL, EVENTS, RAW, EXPIRED, CURRENT
{
} // OutputEventType
