/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.siddhi;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Output Rate</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.siddhi.siddhi.OutputRate#getOp_rate_type <em>Op rate type</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.OutputRate#getEvery <em>Every</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.OutputRate#getTv <em>Tv</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getOutputRate()
 * @model
 * @generated
 */
public interface OutputRate extends OUTPUT, EVENTS, SNAPSHOT
{
  /**
   * Returns the value of the '<em><b>Op rate type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Op rate type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op rate type</em>' containment reference.
   * @see #setOp_rate_type(OutputRateType)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getOutputRate_Op_rate_type()
   * @model containment="true"
   * @generated
   */
  OutputRateType getOp_rate_type();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.OutputRate#getOp_rate_type <em>Op rate type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op rate type</em>' containment reference.
   * @see #getOp_rate_type()
   * @generated
   */
  void setOp_rate_type(OutputRateType value);

  /**
   * Returns the value of the '<em><b>Every</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Every</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Every</em>' containment reference.
   * @see #setEvery(EVERY)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getOutputRate_Every()
   * @model containment="true"
   * @generated
   */
  EVERY getEvery();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.OutputRate#getEvery <em>Every</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Every</em>' containment reference.
   * @see #getEvery()
   * @generated
   */
  void setEvery(EVERY value);

  /**
   * Returns the value of the '<em><b>Tv</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tv</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tv</em>' containment reference.
   * @see #setTv(TimeValue)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getOutputRate_Tv()
   * @model containment="true"
   * @generated
   */
  TimeValue getTv();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.OutputRate#getTv <em>Tv</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tv</em>' containment reference.
   * @see #getTv()
   * @generated
   */
  void setTv(TimeValue value);

} // OutputRate
