/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.siddhi;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pattern Source Chain</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.siddhi.siddhi.PatternSourceChain#getLeft <em>Left</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.PatternSourceChain#getOp <em>Op</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.PatternSourceChain#getRight <em>Right</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.PatternSourceChain#getPsc_2 <em>Psc 2</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.PatternSourceChain#getWt <em>Wt</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.PatternSourceChain#getPs <em>Ps</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getPatternSourceChain()
 * @model
 * @generated
 */
public interface PatternSourceChain extends EObject
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Left</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(PatternSourceChain)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getPatternSourceChain_Left()
   * @model containment="true"
   * @generated
   */
  PatternSourceChain getLeft();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.PatternSourceChain#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(PatternSourceChain value);

  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Op</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see #setOp(String)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getPatternSourceChain_Op()
   * @model
   * @generated
   */
  String getOp();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.PatternSourceChain#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see #getOp()
   * @generated
   */
  void setOp(String value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Right</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(PatternSourceChain)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getPatternSourceChain_Right()
   * @model containment="true"
   * @generated
   */
  PatternSourceChain getRight();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.PatternSourceChain#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(PatternSourceChain value);

  /**
   * Returns the value of the '<em><b>Psc 2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Psc 2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Psc 2</em>' containment reference.
   * @see #setPsc_2(PatternSourceChain)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getPatternSourceChain_Psc_2()
   * @model containment="true"
   * @generated
   */
  PatternSourceChain getPsc_2();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.PatternSourceChain#getPsc_2 <em>Psc 2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Psc 2</em>' containment reference.
   * @see #getPsc_2()
   * @generated
   */
  void setPsc_2(PatternSourceChain value);

  /**
   * Returns the value of the '<em><b>Wt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Wt</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Wt</em>' containment reference.
   * @see #setWt(WithinTime)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getPatternSourceChain_Wt()
   * @model containment="true"
   * @generated
   */
  WithinTime getWt();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.PatternSourceChain#getWt <em>Wt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Wt</em>' containment reference.
   * @see #getWt()
   * @generated
   */
  void setWt(WithinTime value);

  /**
   * Returns the value of the '<em><b>Ps</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ps</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ps</em>' containment reference.
   * @see #setPs(PatternSource)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getPatternSourceChain_Ps()
   * @model containment="true"
   * @generated
   */
  PatternSource getPs();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.PatternSourceChain#getPs <em>Ps</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ps</em>' containment reference.
   * @see #getPs()
   * @generated
   */
  void setPs(PatternSource value);

} // PatternSourceChain
