/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.siddhi;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property Separator</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getPropertySeparator()
 * @model
 * @generated
 */
public interface PropertySeparator extends EObject
{
} // PropertySeparator
