/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.siddhi;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Right Absent Sequence Source1</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.siddhi.siddhi.RightAbsentSequenceSource1#getLeft <em>Left</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.RightAbsentSequenceSource1#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getRightAbsentSequenceSource1()
 * @model
 * @generated
 */
public interface RightAbsentSequenceSource1 extends RightAbsentSequenceSource
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Left</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(RightAbsentSequenceSource)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getRightAbsentSequenceSource1_Left()
   * @model containment="true"
   * @generated
   */
  RightAbsentSequenceSource getLeft();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.RightAbsentSequenceSource1#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(RightAbsentSequenceSource value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Right</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(SequenceSourceChain)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getRightAbsentSequenceSource1_Right()
   * @model containment="true"
   * @generated
   */
  SequenceSourceChain getRight();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.RightAbsentSequenceSource1#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(SequenceSourceChain value);

} // RightAbsentSequenceSource1
