/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.siddhi;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sequence Source Chain</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.siddhi.siddhi.SequenceSourceChain#getLeft <em>Left</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.SequenceSourceChain#getOp <em>Op</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.SequenceSourceChain#getRight <em>Right</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.SequenceSourceChain#getWt1 <em>Wt1</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getSequenceSourceChain()
 * @model
 * @generated
 */
public interface SequenceSourceChain extends EObject
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Left</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(SequenceSourceChain)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getSequenceSourceChain_Left()
   * @model containment="true"
   * @generated
   */
  SequenceSourceChain getLeft();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.SequenceSourceChain#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(SequenceSourceChain value);

  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Op</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see #setOp(String)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getSequenceSourceChain_Op()
   * @model
   * @generated
   */
  String getOp();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.SequenceSourceChain#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see #getOp()
   * @generated
   */
  void setOp(String value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Right</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(SequenceSourceChain)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getSequenceSourceChain_Right()
   * @model containment="true"
   * @generated
   */
  SequenceSourceChain getRight();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.SequenceSourceChain#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(SequenceSourceChain value);

  /**
   * Returns the value of the '<em><b>Wt1</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.siddhi.siddhi.WithinTime}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Wt1</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Wt1</em>' containment reference list.
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getSequenceSourceChain_Wt1()
   * @model containment="true"
   * @generated
   */
  EList<WithinTime> getWt1();

} // SequenceSourceChain
