/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.siddhi;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Standard Stateful Source</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.siddhi.siddhi.StandardStatefulSource#getColl <em>Coll</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.StandardStatefulSource#getZero_or_more <em>Zero or more</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.StandardStatefulSource#getZero_or_one <em>Zero or one</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.StandardStatefulSource#getOne_or_more <em>One or more</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.StandardStatefulSource#getBs <em>Bs</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getStandardStatefulSource()
 * @model
 * @generated
 */
public interface StandardStatefulSource extends PatternCollectionStatefulSource, SequenceSource, SequenceCollectionStatefulSource, Source1OrStandardStatefulSource
{
  /**
   * Returns the value of the '<em><b>Coll</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Coll</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Coll</em>' containment reference.
   * @see #setColl(Collect)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getStandardStatefulSource_Coll()
   * @model containment="true"
   * @generated
   */
  Collect getColl();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.StandardStatefulSource#getColl <em>Coll</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Coll</em>' containment reference.
   * @see #getColl()
   * @generated
   */
  void setColl(Collect value);

  /**
   * Returns the value of the '<em><b>Zero or more</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Zero or more</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Zero or more</em>' attribute.
   * @see #setZero_or_more(String)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getStandardStatefulSource_Zero_or_more()
   * @model
   * @generated
   */
  String getZero_or_more();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.StandardStatefulSource#getZero_or_more <em>Zero or more</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Zero or more</em>' attribute.
   * @see #getZero_or_more()
   * @generated
   */
  void setZero_or_more(String value);

  /**
   * Returns the value of the '<em><b>Zero or one</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Zero or one</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Zero or one</em>' attribute.
   * @see #setZero_or_one(String)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getStandardStatefulSource_Zero_or_one()
   * @model
   * @generated
   */
  String getZero_or_one();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.StandardStatefulSource#getZero_or_one <em>Zero or one</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Zero or one</em>' attribute.
   * @see #getZero_or_one()
   * @generated
   */
  void setZero_or_one(String value);

  /**
   * Returns the value of the '<em><b>One or more</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>One or more</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>One or more</em>' attribute.
   * @see #setOne_or_more(String)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getStandardStatefulSource_One_or_more()
   * @model
   * @generated
   */
  String getOne_or_more();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.StandardStatefulSource#getOne_or_more <em>One or more</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>One or more</em>' attribute.
   * @see #getOne_or_more()
   * @generated
   */
  void setOne_or_more(String value);

  /**
   * Returns the value of the '<em><b>Bs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Bs</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bs</em>' containment reference.
   * @see #setBs(BasicSource)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getStandardStatefulSource_Bs()
   * @model containment="true"
   * @generated
   */
  BasicSource getBs();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.StandardStatefulSource#getBs <em>Bs</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bs</em>' containment reference.
   * @see #getBs()
   * @generated
   */
  void setBs(BasicSource value);

} // StandardStatefulSource
