/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.siddhi;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>WINDOW</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.siddhi.siddhi.WINDOW#getWindow <em>Window</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getWINDOW()
 * @model
 * @generated
 */
public interface WINDOW extends EObject
{
  /**
   * Returns the value of the '<em><b>Window</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Window</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Window</em>' attribute.
   * @see #setWindow(String)
   * @see org.xtext.example.siddhi.siddhi.SiddhiPackage#getWINDOW_Window()
   * @model
   * @generated
   */
  String getWindow();

  /**
   * Sets the value of the '{@link org.xtext.example.siddhi.siddhi.WINDOW#getWindow <em>Window</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Window</em>' attribute.
   * @see #getWindow()
   * @generated
   */
  void setWindow(String value);

} // WINDOW
