/*
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.siddhi.ui.internal.SiddhiActivator;

public class SiddhiUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SiddhiActivator.getInstance().getInjector("org.xtext.example.siddhi.Siddhi");
	}

}
