/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.siddhi.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.siddhi.siddhi.SiddhiPackage;
import org.xtext.example.siddhi.siddhi.aggregation_time_interval;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>aggregation time interval</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class aggregation_time_intervalImpl extends AggregationTimeImpl implements aggregation_time_interval
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected aggregation_time_intervalImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SiddhiPackage.eINSTANCE.getaggregation_time_interval();
  }

} //aggregation_time_intervalImpl
