/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.siddhi.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.siddhi.siddhi.AggregationTime;
import org.xtext.example.siddhi.siddhi.AggregationTimeDuration;
import org.xtext.example.siddhi.siddhi.SiddhiPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Aggregation Time</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.AggregationTimeImpl#getAggrtimeDur <em>Aggrtime Dur</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AggregationTimeImpl extends MinimalEObjectImpl.Container implements AggregationTime
{
  /**
   * The cached value of the '{@link #getAggrtimeDur() <em>Aggrtime Dur</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAggrtimeDur()
   * @generated
   * @ordered
   */
  protected EList<AggregationTimeDuration> aggrtimeDur;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AggregationTimeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SiddhiPackage.eINSTANCE.getAggregationTime();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<AggregationTimeDuration> getAggrtimeDur()
  {
    if (aggrtimeDur == null)
    {
      aggrtimeDur = new EObjectContainmentEList<AggregationTimeDuration>(AggregationTimeDuration.class, this, SiddhiPackage.AGGREGATION_TIME__AGGRTIME_DUR);
    }
    return aggrtimeDur;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SiddhiPackage.AGGREGATION_TIME__AGGRTIME_DUR:
        return ((InternalEList<?>)getAggrtimeDur()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SiddhiPackage.AGGREGATION_TIME__AGGRTIME_DUR:
        return getAggrtimeDur();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SiddhiPackage.AGGREGATION_TIME__AGGRTIME_DUR:
        getAggrtimeDur().clear();
        getAggrtimeDur().addAll((Collection<? extends AggregationTimeDuration>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SiddhiPackage.AGGREGATION_TIME__AGGRTIME_DUR:
        getAggrtimeDur().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SiddhiPackage.AGGREGATION_TIME__AGGRTIME_DUR:
        return aggrtimeDur != null && !aggrtimeDur.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //AggregationTimeImpl
