/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.siddhi.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.siddhi.siddhi.Annotation;
import org.xtext.example.siddhi.siddhi.AnnotationElement;
import org.xtext.example.siddhi.siddhi.Name;
import org.xtext.example.siddhi.siddhi.SiddhiPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Annotation</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.AnnotationImpl#getNa <em>Na</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.AnnotationImpl#getAnnElement <em>Ann Element</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.AnnotationImpl#getAnn <em>Ann</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AnnotationImpl extends MinimalEObjectImpl.Container implements Annotation
{
  /**
   * The cached value of the '{@link #getNa() <em>Na</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNa()
   * @generated
   * @ordered
   */
  protected Name na;

  /**
   * The cached value of the '{@link #getAnnElement() <em>Ann Element</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAnnElement()
   * @generated
   * @ordered
   */
  protected EList<AnnotationElement> annElement;

  /**
   * The cached value of the '{@link #getAnn() <em>Ann</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAnn()
   * @generated
   * @ordered
   */
  protected EList<Annotation> ann;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AnnotationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SiddhiPackage.eINSTANCE.getAnnotation();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Name getNa()
  {
    return na;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNa(Name newNa, NotificationChain msgs)
  {
    Name oldNa = na;
    na = newNa;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SiddhiPackage.ANNOTATION__NA, oldNa, newNa);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNa(Name newNa)
  {
    if (newNa != na)
    {
      NotificationChain msgs = null;
      if (na != null)
        msgs = ((InternalEObject)na).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.ANNOTATION__NA, null, msgs);
      if (newNa != null)
        msgs = ((InternalEObject)newNa).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.ANNOTATION__NA, null, msgs);
      msgs = basicSetNa(newNa, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.ANNOTATION__NA, newNa, newNa));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<AnnotationElement> getAnnElement()
  {
    if (annElement == null)
    {
      annElement = new EObjectContainmentEList<AnnotationElement>(AnnotationElement.class, this, SiddhiPackage.ANNOTATION__ANN_ELEMENT);
    }
    return annElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Annotation> getAnn()
  {
    if (ann == null)
    {
      ann = new EObjectContainmentEList<Annotation>(Annotation.class, this, SiddhiPackage.ANNOTATION__ANN);
    }
    return ann;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SiddhiPackage.ANNOTATION__NA:
        return basicSetNa(null, msgs);
      case SiddhiPackage.ANNOTATION__ANN_ELEMENT:
        return ((InternalEList<?>)getAnnElement()).basicRemove(otherEnd, msgs);
      case SiddhiPackage.ANNOTATION__ANN:
        return ((InternalEList<?>)getAnn()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SiddhiPackage.ANNOTATION__NA:
        return getNa();
      case SiddhiPackage.ANNOTATION__ANN_ELEMENT:
        return getAnnElement();
      case SiddhiPackage.ANNOTATION__ANN:
        return getAnn();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SiddhiPackage.ANNOTATION__NA:
        setNa((Name)newValue);
        return;
      case SiddhiPackage.ANNOTATION__ANN_ELEMENT:
        getAnnElement().clear();
        getAnnElement().addAll((Collection<? extends AnnotationElement>)newValue);
        return;
      case SiddhiPackage.ANNOTATION__ANN:
        getAnn().clear();
        getAnn().addAll((Collection<? extends Annotation>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SiddhiPackage.ANNOTATION__NA:
        setNa((Name)null);
        return;
      case SiddhiPackage.ANNOTATION__ANN_ELEMENT:
        getAnnElement().clear();
        return;
      case SiddhiPackage.ANNOTATION__ANN:
        getAnn().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SiddhiPackage.ANNOTATION__NA:
        return na != null;
      case SiddhiPackage.ANNOTATION__ANN_ELEMENT:
        return annElement != null && !annElement.isEmpty();
      case SiddhiPackage.ANNOTATION__ANN:
        return ann != null && !ann.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //AnnotationImpl
