/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.siddhi.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.siddhi.siddhi.AttributeType;
import org.xtext.example.siddhi.siddhi.BOOL;
import org.xtext.example.siddhi.siddhi.DOUBLE;
import org.xtext.example.siddhi.siddhi.FLOAT;
import org.xtext.example.siddhi.siddhi.INTS;
import org.xtext.example.siddhi.siddhi.LONG;
import org.xtext.example.siddhi.siddhi.OBJECT;
import org.xtext.example.siddhi.siddhi.SiddhiPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Attribute Type</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.AttributeTypeImpl#getInt <em>Int</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.AttributeTypeImpl#getLong <em>Long</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.AttributeTypeImpl#getFloat <em>Float</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.AttributeTypeImpl#getDouble <em>Double</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.AttributeTypeImpl#getBool <em>Bool</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.AttributeTypeImpl#getObject <em>Object</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AttributeTypeImpl extends STRINGSImpl implements AttributeType
{
  /**
   * The default value of the '{@link #getInt() <em>Int</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInt()
   * @generated
   * @ordered
   */
  protected static final String INT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getInt() <em>Int</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInt()
   * @generated
   * @ordered
   */
  protected String int_ = INT_EDEFAULT;

  /**
   * The default value of the '{@link #getLong() <em>Long</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLong()
   * @generated
   * @ordered
   */
  protected static final String LONG_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLong() <em>Long</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLong()
   * @generated
   * @ordered
   */
  protected String long_ = LONG_EDEFAULT;

  /**
   * The default value of the '{@link #getFloat() <em>Float</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFloat()
   * @generated
   * @ordered
   */
  protected static final String FLOAT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFloat() <em>Float</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFloat()
   * @generated
   * @ordered
   */
  protected String float_ = FLOAT_EDEFAULT;

  /**
   * The default value of the '{@link #getDouble() <em>Double</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDouble()
   * @generated
   * @ordered
   */
  protected static final String DOUBLE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDouble() <em>Double</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDouble()
   * @generated
   * @ordered
   */
  protected String double_ = DOUBLE_EDEFAULT;

  /**
   * The default value of the '{@link #getBool() <em>Bool</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBool()
   * @generated
   * @ordered
   */
  protected static final String BOOL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getBool() <em>Bool</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBool()
   * @generated
   * @ordered
   */
  protected String bool = BOOL_EDEFAULT;

  /**
   * The default value of the '{@link #getObject() <em>Object</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getObject()
   * @generated
   * @ordered
   */
  protected static final String OBJECT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getObject() <em>Object</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getObject()
   * @generated
   * @ordered
   */
  protected String object = OBJECT_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AttributeTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SiddhiPackage.eINSTANCE.getAttributeType();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getInt()
  {
    return int_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setInt(String newInt)
  {
    String oldInt = int_;
    int_ = newInt;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.ATTRIBUTE_TYPE__INT, oldInt, int_));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLong()
  {
    return long_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLong(String newLong)
  {
    String oldLong = long_;
    long_ = newLong;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.ATTRIBUTE_TYPE__LONG, oldLong, long_));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getFloat()
  {
    return float_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFloat(String newFloat)
  {
    String oldFloat = float_;
    float_ = newFloat;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.ATTRIBUTE_TYPE__FLOAT, oldFloat, float_));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getDouble()
  {
    return double_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDouble(String newDouble)
  {
    String oldDouble = double_;
    double_ = newDouble;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.ATTRIBUTE_TYPE__DOUBLE, oldDouble, double_));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getBool()
  {
    return bool;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setBool(String newBool)
  {
    String oldBool = bool;
    bool = newBool;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.ATTRIBUTE_TYPE__BOOL, oldBool, bool));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getObject()
  {
    return object;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setObject(String newObject)
  {
    String oldObject = object;
    object = newObject;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.ATTRIBUTE_TYPE__OBJECT, oldObject, object));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SiddhiPackage.ATTRIBUTE_TYPE__INT:
        return getInt();
      case SiddhiPackage.ATTRIBUTE_TYPE__LONG:
        return getLong();
      case SiddhiPackage.ATTRIBUTE_TYPE__FLOAT:
        return getFloat();
      case SiddhiPackage.ATTRIBUTE_TYPE__DOUBLE:
        return getDouble();
      case SiddhiPackage.ATTRIBUTE_TYPE__BOOL:
        return getBool();
      case SiddhiPackage.ATTRIBUTE_TYPE__OBJECT:
        return getObject();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SiddhiPackage.ATTRIBUTE_TYPE__INT:
        setInt((String)newValue);
        return;
      case SiddhiPackage.ATTRIBUTE_TYPE__LONG:
        setLong((String)newValue);
        return;
      case SiddhiPackage.ATTRIBUTE_TYPE__FLOAT:
        setFloat((String)newValue);
        return;
      case SiddhiPackage.ATTRIBUTE_TYPE__DOUBLE:
        setDouble((String)newValue);
        return;
      case SiddhiPackage.ATTRIBUTE_TYPE__BOOL:
        setBool((String)newValue);
        return;
      case SiddhiPackage.ATTRIBUTE_TYPE__OBJECT:
        setObject((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SiddhiPackage.ATTRIBUTE_TYPE__INT:
        setInt(INT_EDEFAULT);
        return;
      case SiddhiPackage.ATTRIBUTE_TYPE__LONG:
        setLong(LONG_EDEFAULT);
        return;
      case SiddhiPackage.ATTRIBUTE_TYPE__FLOAT:
        setFloat(FLOAT_EDEFAULT);
        return;
      case SiddhiPackage.ATTRIBUTE_TYPE__DOUBLE:
        setDouble(DOUBLE_EDEFAULT);
        return;
      case SiddhiPackage.ATTRIBUTE_TYPE__BOOL:
        setBool(BOOL_EDEFAULT);
        return;
      case SiddhiPackage.ATTRIBUTE_TYPE__OBJECT:
        setObject(OBJECT_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SiddhiPackage.ATTRIBUTE_TYPE__INT:
        return INT_EDEFAULT == null ? int_ != null : !INT_EDEFAULT.equals(int_);
      case SiddhiPackage.ATTRIBUTE_TYPE__LONG:
        return LONG_EDEFAULT == null ? long_ != null : !LONG_EDEFAULT.equals(long_);
      case SiddhiPackage.ATTRIBUTE_TYPE__FLOAT:
        return FLOAT_EDEFAULT == null ? float_ != null : !FLOAT_EDEFAULT.equals(float_);
      case SiddhiPackage.ATTRIBUTE_TYPE__DOUBLE:
        return DOUBLE_EDEFAULT == null ? double_ != null : !DOUBLE_EDEFAULT.equals(double_);
      case SiddhiPackage.ATTRIBUTE_TYPE__BOOL:
        return BOOL_EDEFAULT == null ? bool != null : !BOOL_EDEFAULT.equals(bool);
      case SiddhiPackage.ATTRIBUTE_TYPE__OBJECT:
        return OBJECT_EDEFAULT == null ? object != null : !OBJECT_EDEFAULT.equals(object);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int eBaseStructuralFeatureID(int derivedFeatureID, Class<?> baseClass)
  {
    if (baseClass == INTS.class)
    {
      switch (derivedFeatureID)
      {
        case SiddhiPackage.ATTRIBUTE_TYPE__INT: return SiddhiPackage.INTS__INT;
        default: return -1;
      }
    }
    if (baseClass == LONG.class)
    {
      switch (derivedFeatureID)
      {
        case SiddhiPackage.ATTRIBUTE_TYPE__LONG: return SiddhiPackage.LONG__LONG;
        default: return -1;
      }
    }
    if (baseClass == FLOAT.class)
    {
      switch (derivedFeatureID)
      {
        case SiddhiPackage.ATTRIBUTE_TYPE__FLOAT: return SiddhiPackage.FLOAT__FLOAT;
        default: return -1;
      }
    }
    if (baseClass == DOUBLE.class)
    {
      switch (derivedFeatureID)
      {
        case SiddhiPackage.ATTRIBUTE_TYPE__DOUBLE: return SiddhiPackage.DOUBLE__DOUBLE;
        default: return -1;
      }
    }
    if (baseClass == BOOL.class)
    {
      switch (derivedFeatureID)
      {
        case SiddhiPackage.ATTRIBUTE_TYPE__BOOL: return SiddhiPackage.BOOL__BOOL;
        default: return -1;
      }
    }
    if (baseClass == OBJECT.class)
    {
      switch (derivedFeatureID)
      {
        case SiddhiPackage.ATTRIBUTE_TYPE__OBJECT: return SiddhiPackage.OBJECT__OBJECT;
        default: return -1;
      }
    }
    return super.eBaseStructuralFeatureID(derivedFeatureID, baseClass);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int eDerivedStructuralFeatureID(int baseFeatureID, Class<?> baseClass)
  {
    if (baseClass == INTS.class)
    {
      switch (baseFeatureID)
      {
        case SiddhiPackage.INTS__INT: return SiddhiPackage.ATTRIBUTE_TYPE__INT;
        default: return -1;
      }
    }
    if (baseClass == LONG.class)
    {
      switch (baseFeatureID)
      {
        case SiddhiPackage.LONG__LONG: return SiddhiPackage.ATTRIBUTE_TYPE__LONG;
        default: return -1;
      }
    }
    if (baseClass == FLOAT.class)
    {
      switch (baseFeatureID)
      {
        case SiddhiPackage.FLOAT__FLOAT: return SiddhiPackage.ATTRIBUTE_TYPE__FLOAT;
        default: return -1;
      }
    }
    if (baseClass == DOUBLE.class)
    {
      switch (baseFeatureID)
      {
        case SiddhiPackage.DOUBLE__DOUBLE: return SiddhiPackage.ATTRIBUTE_TYPE__DOUBLE;
        default: return -1;
      }
    }
    if (baseClass == BOOL.class)
    {
      switch (baseFeatureID)
      {
        case SiddhiPackage.BOOL__BOOL: return SiddhiPackage.ATTRIBUTE_TYPE__BOOL;
        default: return -1;
      }
    }
    if (baseClass == OBJECT.class)
    {
      switch (baseFeatureID)
      {
        case SiddhiPackage.OBJECT__OBJECT: return SiddhiPackage.ATTRIBUTE_TYPE__OBJECT;
        default: return -1;
      }
    }
    return super.eDerivedStructuralFeatureID(baseFeatureID, baseClass);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (int: ");
    result.append(int_);
    result.append(", long: ");
    result.append(long_);
    result.append(", float: ");
    result.append(float_);
    result.append(", double: ");
    result.append(double_);
    result.append(", bool: ");
    result.append(bool);
    result.append(", object: ");
    result.append(object);
    result.append(')');
    return result.toString();
  }

} //AttributeTypeImpl
