/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.siddhi.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.siddhi.siddhi.BasicSourceStreamHandlers1;
import org.xtext.example.siddhi.siddhi.Expression;
import org.xtext.example.siddhi.siddhi.FunctionOperation;
import org.xtext.example.siddhi.siddhi.SiddhiPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Basic Source Stream Handlers1</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.BasicSourceStreamHandlers1Impl#getExp <em>Exp</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.BasicSourceStreamHandlers1Impl#getFo <em>Fo</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.BasicSourceStreamHandlers1Impl#getFunc_op <em>Func op</em>}</li>
 * </ul>
 *
 * @generated
 */
public class BasicSourceStreamHandlers1Impl extends WINDOWImpl implements BasicSourceStreamHandlers1
{
  /**
   * The cached value of the '{@link #getExp() <em>Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExp()
   * @generated
   * @ordered
   */
  protected Expression exp;

  /**
   * The cached value of the '{@link #getFo() <em>Fo</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFo()
   * @generated
   * @ordered
   */
  protected FunctionOperation fo;

  /**
   * The cached value of the '{@link #getFunc_op() <em>Func op</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFunc_op()
   * @generated
   * @ordered
   */
  protected FunctionOperation func_op;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BasicSourceStreamHandlers1Impl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SiddhiPackage.eINSTANCE.getBasicSourceStreamHandlers1();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Expression getExp()
  {
    return exp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExp(Expression newExp, NotificationChain msgs)
  {
    Expression oldExp = exp;
    exp = newExp;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SiddhiPackage.BASIC_SOURCE_STREAM_HANDLERS1__EXP, oldExp, newExp);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setExp(Expression newExp)
  {
    if (newExp != exp)
    {
      NotificationChain msgs = null;
      if (exp != null)
        msgs = ((InternalEObject)exp).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.BASIC_SOURCE_STREAM_HANDLERS1__EXP, null, msgs);
      if (newExp != null)
        msgs = ((InternalEObject)newExp).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.BASIC_SOURCE_STREAM_HANDLERS1__EXP, null, msgs);
      msgs = basicSetExp(newExp, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.BASIC_SOURCE_STREAM_HANDLERS1__EXP, newExp, newExp));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FunctionOperation getFo()
  {
    return fo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFo(FunctionOperation newFo, NotificationChain msgs)
  {
    FunctionOperation oldFo = fo;
    fo = newFo;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SiddhiPackage.BASIC_SOURCE_STREAM_HANDLERS1__FO, oldFo, newFo);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFo(FunctionOperation newFo)
  {
    if (newFo != fo)
    {
      NotificationChain msgs = null;
      if (fo != null)
        msgs = ((InternalEObject)fo).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.BASIC_SOURCE_STREAM_HANDLERS1__FO, null, msgs);
      if (newFo != null)
        msgs = ((InternalEObject)newFo).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.BASIC_SOURCE_STREAM_HANDLERS1__FO, null, msgs);
      msgs = basicSetFo(newFo, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.BASIC_SOURCE_STREAM_HANDLERS1__FO, newFo, newFo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FunctionOperation getFunc_op()
  {
    return func_op;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFunc_op(FunctionOperation newFunc_op, NotificationChain msgs)
  {
    FunctionOperation oldFunc_op = func_op;
    func_op = newFunc_op;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SiddhiPackage.BASIC_SOURCE_STREAM_HANDLERS1__FUNC_OP, oldFunc_op, newFunc_op);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFunc_op(FunctionOperation newFunc_op)
  {
    if (newFunc_op != func_op)
    {
      NotificationChain msgs = null;
      if (func_op != null)
        msgs = ((InternalEObject)func_op).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.BASIC_SOURCE_STREAM_HANDLERS1__FUNC_OP, null, msgs);
      if (newFunc_op != null)
        msgs = ((InternalEObject)newFunc_op).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.BASIC_SOURCE_STREAM_HANDLERS1__FUNC_OP, null, msgs);
      msgs = basicSetFunc_op(newFunc_op, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.BASIC_SOURCE_STREAM_HANDLERS1__FUNC_OP, newFunc_op, newFunc_op));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SiddhiPackage.BASIC_SOURCE_STREAM_HANDLERS1__EXP:
        return basicSetExp(null, msgs);
      case SiddhiPackage.BASIC_SOURCE_STREAM_HANDLERS1__FO:
        return basicSetFo(null, msgs);
      case SiddhiPackage.BASIC_SOURCE_STREAM_HANDLERS1__FUNC_OP:
        return basicSetFunc_op(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SiddhiPackage.BASIC_SOURCE_STREAM_HANDLERS1__EXP:
        return getExp();
      case SiddhiPackage.BASIC_SOURCE_STREAM_HANDLERS1__FO:
        return getFo();
      case SiddhiPackage.BASIC_SOURCE_STREAM_HANDLERS1__FUNC_OP:
        return getFunc_op();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SiddhiPackage.BASIC_SOURCE_STREAM_HANDLERS1__EXP:
        setExp((Expression)newValue);
        return;
      case SiddhiPackage.BASIC_SOURCE_STREAM_HANDLERS1__FO:
        setFo((FunctionOperation)newValue);
        return;
      case SiddhiPackage.BASIC_SOURCE_STREAM_HANDLERS1__FUNC_OP:
        setFunc_op((FunctionOperation)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SiddhiPackage.BASIC_SOURCE_STREAM_HANDLERS1__EXP:
        setExp((Expression)null);
        return;
      case SiddhiPackage.BASIC_SOURCE_STREAM_HANDLERS1__FO:
        setFo((FunctionOperation)null);
        return;
      case SiddhiPackage.BASIC_SOURCE_STREAM_HANDLERS1__FUNC_OP:
        setFunc_op((FunctionOperation)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SiddhiPackage.BASIC_SOURCE_STREAM_HANDLERS1__EXP:
        return exp != null;
      case SiddhiPackage.BASIC_SOURCE_STREAM_HANDLERS1__FO:
        return fo != null;
      case SiddhiPackage.BASIC_SOURCE_STREAM_HANDLERS1__FUNC_OP:
        return func_op != null;
    }
    return super.eIsSet(featureID);
  }

} //BasicSourceStreamHandlers1Impl
