/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.siddhi.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.siddhi.siddhi.BasicSource;
import org.xtext.example.siddhi.siddhi.BasicSourceStreamHandlers;
import org.xtext.example.siddhi.siddhi.SiddhiPackage;
import org.xtext.example.siddhi.siddhi.Source;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Basic Source</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.BasicSourceImpl#getSrc <em>Src</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.BasicSourceImpl#getBasic_ss_handlers <em>Basic ss handlers</em>}</li>
 * </ul>
 *
 * @generated
 */
public class BasicSourceImpl extends MinimalEObjectImpl.Container implements BasicSource
{
  /**
   * The cached value of the '{@link #getSrc() <em>Src</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSrc()
   * @generated
   * @ordered
   */
  protected Source src;

  /**
   * The cached value of the '{@link #getBasic_ss_handlers() <em>Basic ss handlers</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBasic_ss_handlers()
   * @generated
   * @ordered
   */
  protected BasicSourceStreamHandlers basic_ss_handlers;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BasicSourceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SiddhiPackage.eINSTANCE.getBasicSource();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Source getSrc()
  {
    return src;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSrc(Source newSrc, NotificationChain msgs)
  {
    Source oldSrc = src;
    src = newSrc;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SiddhiPackage.BASIC_SOURCE__SRC, oldSrc, newSrc);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSrc(Source newSrc)
  {
    if (newSrc != src)
    {
      NotificationChain msgs = null;
      if (src != null)
        msgs = ((InternalEObject)src).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.BASIC_SOURCE__SRC, null, msgs);
      if (newSrc != null)
        msgs = ((InternalEObject)newSrc).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.BASIC_SOURCE__SRC, null, msgs);
      msgs = basicSetSrc(newSrc, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.BASIC_SOURCE__SRC, newSrc, newSrc));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BasicSourceStreamHandlers getBasic_ss_handlers()
  {
    return basic_ss_handlers;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetBasic_ss_handlers(BasicSourceStreamHandlers newBasic_ss_handlers, NotificationChain msgs)
  {
    BasicSourceStreamHandlers oldBasic_ss_handlers = basic_ss_handlers;
    basic_ss_handlers = newBasic_ss_handlers;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SiddhiPackage.BASIC_SOURCE__BASIC_SS_HANDLERS, oldBasic_ss_handlers, newBasic_ss_handlers);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setBasic_ss_handlers(BasicSourceStreamHandlers newBasic_ss_handlers)
  {
    if (newBasic_ss_handlers != basic_ss_handlers)
    {
      NotificationChain msgs = null;
      if (basic_ss_handlers != null)
        msgs = ((InternalEObject)basic_ss_handlers).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.BASIC_SOURCE__BASIC_SS_HANDLERS, null, msgs);
      if (newBasic_ss_handlers != null)
        msgs = ((InternalEObject)newBasic_ss_handlers).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.BASIC_SOURCE__BASIC_SS_HANDLERS, null, msgs);
      msgs = basicSetBasic_ss_handlers(newBasic_ss_handlers, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.BASIC_SOURCE__BASIC_SS_HANDLERS, newBasic_ss_handlers, newBasic_ss_handlers));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SiddhiPackage.BASIC_SOURCE__SRC:
        return basicSetSrc(null, msgs);
      case SiddhiPackage.BASIC_SOURCE__BASIC_SS_HANDLERS:
        return basicSetBasic_ss_handlers(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SiddhiPackage.BASIC_SOURCE__SRC:
        return getSrc();
      case SiddhiPackage.BASIC_SOURCE__BASIC_SS_HANDLERS:
        return getBasic_ss_handlers();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SiddhiPackage.BASIC_SOURCE__SRC:
        setSrc((Source)newValue);
        return;
      case SiddhiPackage.BASIC_SOURCE__BASIC_SS_HANDLERS:
        setBasic_ss_handlers((BasicSourceStreamHandlers)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SiddhiPackage.BASIC_SOURCE__SRC:
        setSrc((Source)null);
        return;
      case SiddhiPackage.BASIC_SOURCE__BASIC_SS_HANDLERS:
        setBasic_ss_handlers((BasicSourceStreamHandlers)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SiddhiPackage.BASIC_SOURCE__SRC:
        return src != null;
      case SiddhiPackage.BASIC_SOURCE__BASIC_SS_HANDLERS:
        return basic_ss_handlers != null;
    }
    return super.eIsSet(featureID);
  }

} //BasicSourceImpl
