/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.siddhi.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.siddhi.siddhi.AGGREGATE;
import org.xtext.example.siddhi.siddhi.AGGREGATION;
import org.xtext.example.siddhi.siddhi.AggregationTime;
import org.xtext.example.siddhi.siddhi.Annotation;
import org.xtext.example.siddhi.siddhi.AttributeReference;
import org.xtext.example.siddhi.siddhi.BY;
import org.xtext.example.siddhi.siddhi.DefinitionAggregation;
import org.xtext.example.siddhi.siddhi.EVERY;
import org.xtext.example.siddhi.siddhi.FROM;
import org.xtext.example.siddhi.siddhi.GroupByQuerySelection;
import org.xtext.example.siddhi.siddhi.SiddhiPackage;
import org.xtext.example.siddhi.siddhi.Source1;
import org.xtext.example.siddhi.siddhi.StandardStream;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Definition Aggregation</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.DefinitionAggregationImpl#getAggre <em>Aggre</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.DefinitionAggregationImpl#getFrom <em>From</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.DefinitionAggregationImpl#getAgrregate <em>Agrregate</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.DefinitionAggregationImpl#getBy <em>By</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.DefinitionAggregationImpl#getAnn <em>Ann</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.DefinitionAggregationImpl#getSrc <em>Src</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.DefinitionAggregationImpl#getStdStream <em>Std Stream</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.DefinitionAggregationImpl#getGroupByQuerySel <em>Group By Query Sel</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.DefinitionAggregationImpl#getAttrRef <em>Attr Ref</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.DefinitionAggregationImpl#getEve <em>Eve</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.DefinitionAggregationImpl#getAggrTime <em>Aggr Time</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DefinitionAggregationImpl extends DEFINEImpl implements DefinitionAggregation
{
  /**
   * The default value of the '{@link #getAggre() <em>Aggre</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAggre()
   * @generated
   * @ordered
   */
  protected static final String AGGRE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAggre() <em>Aggre</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAggre()
   * @generated
   * @ordered
   */
  protected String aggre = AGGRE_EDEFAULT;

  /**
   * The default value of the '{@link #getFrom() <em>From</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFrom()
   * @generated
   * @ordered
   */
  protected static final String FROM_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFrom() <em>From</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFrom()
   * @generated
   * @ordered
   */
  protected String from = FROM_EDEFAULT;

  /**
   * The default value of the '{@link #getAgrregate() <em>Agrregate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAgrregate()
   * @generated
   * @ordered
   */
  protected static final String AGRREGATE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAgrregate() <em>Agrregate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAgrregate()
   * @generated
   * @ordered
   */
  protected String agrregate = AGRREGATE_EDEFAULT;

  /**
   * The default value of the '{@link #getBy() <em>By</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBy()
   * @generated
   * @ordered
   */
  protected static final String BY_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getBy() <em>By</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBy()
   * @generated
   * @ordered
   */
  protected String by = BY_EDEFAULT;

  /**
   * The cached value of the '{@link #getAnn() <em>Ann</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAnn()
   * @generated
   * @ordered
   */
  protected EList<Annotation> ann;

  /**
   * The cached value of the '{@link #getSrc() <em>Src</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSrc()
   * @generated
   * @ordered
   */
  protected Source1 src;

  /**
   * The cached value of the '{@link #getStdStream() <em>Std Stream</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStdStream()
   * @generated
   * @ordered
   */
  protected StandardStream stdStream;

  /**
   * The cached value of the '{@link #getGroupByQuerySel() <em>Group By Query Sel</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGroupByQuerySel()
   * @generated
   * @ordered
   */
  protected GroupByQuerySelection groupByQuerySel;

  /**
   * The cached value of the '{@link #getAttrRef() <em>Attr Ref</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAttrRef()
   * @generated
   * @ordered
   */
  protected AttributeReference attrRef;

  /**
   * The cached value of the '{@link #getEve() <em>Eve</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEve()
   * @generated
   * @ordered
   */
  protected EVERY eve;

  /**
   * The cached value of the '{@link #getAggrTime() <em>Aggr Time</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAggrTime()
   * @generated
   * @ordered
   */
  protected AggregationTime aggrTime;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DefinitionAggregationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SiddhiPackage.eINSTANCE.getDefinitionAggregation();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getAggre()
  {
    return aggre;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAggre(String newAggre)
  {
    String oldAggre = aggre;
    aggre = newAggre;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.DEFINITION_AGGREGATION__AGGRE, oldAggre, aggre));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getFrom()
  {
    return from;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFrom(String newFrom)
  {
    String oldFrom = from;
    from = newFrom;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.DEFINITION_AGGREGATION__FROM, oldFrom, from));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getAgrregate()
  {
    return agrregate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAgrregate(String newAgrregate)
  {
    String oldAgrregate = agrregate;
    agrregate = newAgrregate;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.DEFINITION_AGGREGATION__AGRREGATE, oldAgrregate, agrregate));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getBy()
  {
    return by;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setBy(String newBy)
  {
    String oldBy = by;
    by = newBy;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.DEFINITION_AGGREGATION__BY, oldBy, by));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Annotation> getAnn()
  {
    if (ann == null)
    {
      ann = new EObjectContainmentEList<Annotation>(Annotation.class, this, SiddhiPackage.DEFINITION_AGGREGATION__ANN);
    }
    return ann;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Source1 getSrc()
  {
    return src;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSrc(Source1 newSrc, NotificationChain msgs)
  {
    Source1 oldSrc = src;
    src = newSrc;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SiddhiPackage.DEFINITION_AGGREGATION__SRC, oldSrc, newSrc);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSrc(Source1 newSrc)
  {
    if (newSrc != src)
    {
      NotificationChain msgs = null;
      if (src != null)
        msgs = ((InternalEObject)src).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.DEFINITION_AGGREGATION__SRC, null, msgs);
      if (newSrc != null)
        msgs = ((InternalEObject)newSrc).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.DEFINITION_AGGREGATION__SRC, null, msgs);
      msgs = basicSetSrc(newSrc, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.DEFINITION_AGGREGATION__SRC, newSrc, newSrc));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public StandardStream getStdStream()
  {
    return stdStream;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetStdStream(StandardStream newStdStream, NotificationChain msgs)
  {
    StandardStream oldStdStream = stdStream;
    stdStream = newStdStream;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SiddhiPackage.DEFINITION_AGGREGATION__STD_STREAM, oldStdStream, newStdStream);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setStdStream(StandardStream newStdStream)
  {
    if (newStdStream != stdStream)
    {
      NotificationChain msgs = null;
      if (stdStream != null)
        msgs = ((InternalEObject)stdStream).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.DEFINITION_AGGREGATION__STD_STREAM, null, msgs);
      if (newStdStream != null)
        msgs = ((InternalEObject)newStdStream).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.DEFINITION_AGGREGATION__STD_STREAM, null, msgs);
      msgs = basicSetStdStream(newStdStream, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.DEFINITION_AGGREGATION__STD_STREAM, newStdStream, newStdStream));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GroupByQuerySelection getGroupByQuerySel()
  {
    return groupByQuerySel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetGroupByQuerySel(GroupByQuerySelection newGroupByQuerySel, NotificationChain msgs)
  {
    GroupByQuerySelection oldGroupByQuerySel = groupByQuerySel;
    groupByQuerySel = newGroupByQuerySel;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SiddhiPackage.DEFINITION_AGGREGATION__GROUP_BY_QUERY_SEL, oldGroupByQuerySel, newGroupByQuerySel);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setGroupByQuerySel(GroupByQuerySelection newGroupByQuerySel)
  {
    if (newGroupByQuerySel != groupByQuerySel)
    {
      NotificationChain msgs = null;
      if (groupByQuerySel != null)
        msgs = ((InternalEObject)groupByQuerySel).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.DEFINITION_AGGREGATION__GROUP_BY_QUERY_SEL, null, msgs);
      if (newGroupByQuerySel != null)
        msgs = ((InternalEObject)newGroupByQuerySel).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.DEFINITION_AGGREGATION__GROUP_BY_QUERY_SEL, null, msgs);
      msgs = basicSetGroupByQuerySel(newGroupByQuerySel, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.DEFINITION_AGGREGATION__GROUP_BY_QUERY_SEL, newGroupByQuerySel, newGroupByQuerySel));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AttributeReference getAttrRef()
  {
    return attrRef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAttrRef(AttributeReference newAttrRef, NotificationChain msgs)
  {
    AttributeReference oldAttrRef = attrRef;
    attrRef = newAttrRef;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SiddhiPackage.DEFINITION_AGGREGATION__ATTR_REF, oldAttrRef, newAttrRef);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAttrRef(AttributeReference newAttrRef)
  {
    if (newAttrRef != attrRef)
    {
      NotificationChain msgs = null;
      if (attrRef != null)
        msgs = ((InternalEObject)attrRef).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.DEFINITION_AGGREGATION__ATTR_REF, null, msgs);
      if (newAttrRef != null)
        msgs = ((InternalEObject)newAttrRef).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.DEFINITION_AGGREGATION__ATTR_REF, null, msgs);
      msgs = basicSetAttrRef(newAttrRef, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.DEFINITION_AGGREGATION__ATTR_REF, newAttrRef, newAttrRef));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EVERY getEve()
  {
    return eve;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetEve(EVERY newEve, NotificationChain msgs)
  {
    EVERY oldEve = eve;
    eve = newEve;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SiddhiPackage.DEFINITION_AGGREGATION__EVE, oldEve, newEve);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setEve(EVERY newEve)
  {
    if (newEve != eve)
    {
      NotificationChain msgs = null;
      if (eve != null)
        msgs = ((InternalEObject)eve).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.DEFINITION_AGGREGATION__EVE, null, msgs);
      if (newEve != null)
        msgs = ((InternalEObject)newEve).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.DEFINITION_AGGREGATION__EVE, null, msgs);
      msgs = basicSetEve(newEve, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.DEFINITION_AGGREGATION__EVE, newEve, newEve));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AggregationTime getAggrTime()
  {
    return aggrTime;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAggrTime(AggregationTime newAggrTime, NotificationChain msgs)
  {
    AggregationTime oldAggrTime = aggrTime;
    aggrTime = newAggrTime;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SiddhiPackage.DEFINITION_AGGREGATION__AGGR_TIME, oldAggrTime, newAggrTime);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAggrTime(AggregationTime newAggrTime)
  {
    if (newAggrTime != aggrTime)
    {
      NotificationChain msgs = null;
      if (aggrTime != null)
        msgs = ((InternalEObject)aggrTime).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.DEFINITION_AGGREGATION__AGGR_TIME, null, msgs);
      if (newAggrTime != null)
        msgs = ((InternalEObject)newAggrTime).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.DEFINITION_AGGREGATION__AGGR_TIME, null, msgs);
      msgs = basicSetAggrTime(newAggrTime, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.DEFINITION_AGGREGATION__AGGR_TIME, newAggrTime, newAggrTime));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SiddhiPackage.DEFINITION_AGGREGATION__ANN:
        return ((InternalEList<?>)getAnn()).basicRemove(otherEnd, msgs);
      case SiddhiPackage.DEFINITION_AGGREGATION__SRC:
        return basicSetSrc(null, msgs);
      case SiddhiPackage.DEFINITION_AGGREGATION__STD_STREAM:
        return basicSetStdStream(null, msgs);
      case SiddhiPackage.DEFINITION_AGGREGATION__GROUP_BY_QUERY_SEL:
        return basicSetGroupByQuerySel(null, msgs);
      case SiddhiPackage.DEFINITION_AGGREGATION__ATTR_REF:
        return basicSetAttrRef(null, msgs);
      case SiddhiPackage.DEFINITION_AGGREGATION__EVE:
        return basicSetEve(null, msgs);
      case SiddhiPackage.DEFINITION_AGGREGATION__AGGR_TIME:
        return basicSetAggrTime(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SiddhiPackage.DEFINITION_AGGREGATION__AGGRE:
        return getAggre();
      case SiddhiPackage.DEFINITION_AGGREGATION__FROM:
        return getFrom();
      case SiddhiPackage.DEFINITION_AGGREGATION__AGRREGATE:
        return getAgrregate();
      case SiddhiPackage.DEFINITION_AGGREGATION__BY:
        return getBy();
      case SiddhiPackage.DEFINITION_AGGREGATION__ANN:
        return getAnn();
      case SiddhiPackage.DEFINITION_AGGREGATION__SRC:
        return getSrc();
      case SiddhiPackage.DEFINITION_AGGREGATION__STD_STREAM:
        return getStdStream();
      case SiddhiPackage.DEFINITION_AGGREGATION__GROUP_BY_QUERY_SEL:
        return getGroupByQuerySel();
      case SiddhiPackage.DEFINITION_AGGREGATION__ATTR_REF:
        return getAttrRef();
      case SiddhiPackage.DEFINITION_AGGREGATION__EVE:
        return getEve();
      case SiddhiPackage.DEFINITION_AGGREGATION__AGGR_TIME:
        return getAggrTime();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SiddhiPackage.DEFINITION_AGGREGATION__AGGRE:
        setAggre((String)newValue);
        return;
      case SiddhiPackage.DEFINITION_AGGREGATION__FROM:
        setFrom((String)newValue);
        return;
      case SiddhiPackage.DEFINITION_AGGREGATION__AGRREGATE:
        setAgrregate((String)newValue);
        return;
      case SiddhiPackage.DEFINITION_AGGREGATION__BY:
        setBy((String)newValue);
        return;
      case SiddhiPackage.DEFINITION_AGGREGATION__ANN:
        getAnn().clear();
        getAnn().addAll((Collection<? extends Annotation>)newValue);
        return;
      case SiddhiPackage.DEFINITION_AGGREGATION__SRC:
        setSrc((Source1)newValue);
        return;
      case SiddhiPackage.DEFINITION_AGGREGATION__STD_STREAM:
        setStdStream((StandardStream)newValue);
        return;
      case SiddhiPackage.DEFINITION_AGGREGATION__GROUP_BY_QUERY_SEL:
        setGroupByQuerySel((GroupByQuerySelection)newValue);
        return;
      case SiddhiPackage.DEFINITION_AGGREGATION__ATTR_REF:
        setAttrRef((AttributeReference)newValue);
        return;
      case SiddhiPackage.DEFINITION_AGGREGATION__EVE:
        setEve((EVERY)newValue);
        return;
      case SiddhiPackage.DEFINITION_AGGREGATION__AGGR_TIME:
        setAggrTime((AggregationTime)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SiddhiPackage.DEFINITION_AGGREGATION__AGGRE:
        setAggre(AGGRE_EDEFAULT);
        return;
      case SiddhiPackage.DEFINITION_AGGREGATION__FROM:
        setFrom(FROM_EDEFAULT);
        return;
      case SiddhiPackage.DEFINITION_AGGREGATION__AGRREGATE:
        setAgrregate(AGRREGATE_EDEFAULT);
        return;
      case SiddhiPackage.DEFINITION_AGGREGATION__BY:
        setBy(BY_EDEFAULT);
        return;
      case SiddhiPackage.DEFINITION_AGGREGATION__ANN:
        getAnn().clear();
        return;
      case SiddhiPackage.DEFINITION_AGGREGATION__SRC:
        setSrc((Source1)null);
        return;
      case SiddhiPackage.DEFINITION_AGGREGATION__STD_STREAM:
        setStdStream((StandardStream)null);
        return;
      case SiddhiPackage.DEFINITION_AGGREGATION__GROUP_BY_QUERY_SEL:
        setGroupByQuerySel((GroupByQuerySelection)null);
        return;
      case SiddhiPackage.DEFINITION_AGGREGATION__ATTR_REF:
        setAttrRef((AttributeReference)null);
        return;
      case SiddhiPackage.DEFINITION_AGGREGATION__EVE:
        setEve((EVERY)null);
        return;
      case SiddhiPackage.DEFINITION_AGGREGATION__AGGR_TIME:
        setAggrTime((AggregationTime)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SiddhiPackage.DEFINITION_AGGREGATION__AGGRE:
        return AGGRE_EDEFAULT == null ? aggre != null : !AGGRE_EDEFAULT.equals(aggre);
      case SiddhiPackage.DEFINITION_AGGREGATION__FROM:
        return FROM_EDEFAULT == null ? from != null : !FROM_EDEFAULT.equals(from);
      case SiddhiPackage.DEFINITION_AGGREGATION__AGRREGATE:
        return AGRREGATE_EDEFAULT == null ? agrregate != null : !AGRREGATE_EDEFAULT.equals(agrregate);
      case SiddhiPackage.DEFINITION_AGGREGATION__BY:
        return BY_EDEFAULT == null ? by != null : !BY_EDEFAULT.equals(by);
      case SiddhiPackage.DEFINITION_AGGREGATION__ANN:
        return ann != null && !ann.isEmpty();
      case SiddhiPackage.DEFINITION_AGGREGATION__SRC:
        return src != null;
      case SiddhiPackage.DEFINITION_AGGREGATION__STD_STREAM:
        return stdStream != null;
      case SiddhiPackage.DEFINITION_AGGREGATION__GROUP_BY_QUERY_SEL:
        return groupByQuerySel != null;
      case SiddhiPackage.DEFINITION_AGGREGATION__ATTR_REF:
        return attrRef != null;
      case SiddhiPackage.DEFINITION_AGGREGATION__EVE:
        return eve != null;
      case SiddhiPackage.DEFINITION_AGGREGATION__AGGR_TIME:
        return aggrTime != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int eBaseStructuralFeatureID(int derivedFeatureID, Class<?> baseClass)
  {
    if (baseClass == AGGREGATION.class)
    {
      switch (derivedFeatureID)
      {
        case SiddhiPackage.DEFINITION_AGGREGATION__AGGRE: return SiddhiPackage.AGGREGATION__AGGRE;
        default: return -1;
      }
    }
    if (baseClass == FROM.class)
    {
      switch (derivedFeatureID)
      {
        case SiddhiPackage.DEFINITION_AGGREGATION__FROM: return SiddhiPackage.FROM__FROM;
        default: return -1;
      }
    }
    if (baseClass == AGGREGATE.class)
    {
      switch (derivedFeatureID)
      {
        case SiddhiPackage.DEFINITION_AGGREGATION__AGRREGATE: return SiddhiPackage.AGGREGATE__AGRREGATE;
        default: return -1;
      }
    }
    if (baseClass == BY.class)
    {
      switch (derivedFeatureID)
      {
        case SiddhiPackage.DEFINITION_AGGREGATION__BY: return SiddhiPackage.BY__BY;
        default: return -1;
      }
    }
    return super.eBaseStructuralFeatureID(derivedFeatureID, baseClass);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int eDerivedStructuralFeatureID(int baseFeatureID, Class<?> baseClass)
  {
    if (baseClass == AGGREGATION.class)
    {
      switch (baseFeatureID)
      {
        case SiddhiPackage.AGGREGATION__AGGRE: return SiddhiPackage.DEFINITION_AGGREGATION__AGGRE;
        default: return -1;
      }
    }
    if (baseClass == FROM.class)
    {
      switch (baseFeatureID)
      {
        case SiddhiPackage.FROM__FROM: return SiddhiPackage.DEFINITION_AGGREGATION__FROM;
        default: return -1;
      }
    }
    if (baseClass == AGGREGATE.class)
    {
      switch (baseFeatureID)
      {
        case SiddhiPackage.AGGREGATE__AGRREGATE: return SiddhiPackage.DEFINITION_AGGREGATION__AGRREGATE;
        default: return -1;
      }
    }
    if (baseClass == BY.class)
    {
      switch (baseFeatureID)
      {
        case SiddhiPackage.BY__BY: return SiddhiPackage.DEFINITION_AGGREGATION__BY;
        default: return -1;
      }
    }
    return super.eDerivedStructuralFeatureID(baseFeatureID, baseClass);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (aggre: ");
    result.append(aggre);
    result.append(", from: ");
    result.append(from);
    result.append(", agrregate: ");
    result.append(agrregate);
    result.append(", by: ");
    result.append(by);
    result.append(')');
    return result.toString();
  }

} //DefinitionAggregationImpl
