/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.siddhi.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.siddhi.siddhi.AT;
import org.xtext.example.siddhi.siddhi.DefinitionTrigger;
import org.xtext.example.siddhi.siddhi.EVERY;
import org.xtext.example.siddhi.siddhi.SiddhiPackage;
import org.xtext.example.siddhi.siddhi.StringValue;
import org.xtext.example.siddhi.siddhi.TRIGGER;
import org.xtext.example.siddhi.siddhi.TimeValue;
import org.xtext.example.siddhi.siddhi.TriggerName;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Definition Trigger</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.DefinitionTriggerImpl#getTrigger <em>Trigger</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.DefinitionTriggerImpl#getAt <em>At</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.DefinitionTriggerImpl#getTn <em>Tn</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.DefinitionTriggerImpl#getEvery <em>Every</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.DefinitionTriggerImpl#getTv <em>Tv</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.DefinitionTriggerImpl#getSv <em>Sv</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DefinitionTriggerImpl extends DEFINEImpl implements DefinitionTrigger
{
  /**
   * The default value of the '{@link #getTrigger() <em>Trigger</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTrigger()
   * @generated
   * @ordered
   */
  protected static final String TRIGGER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTrigger() <em>Trigger</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTrigger()
   * @generated
   * @ordered
   */
  protected String trigger = TRIGGER_EDEFAULT;

  /**
   * The default value of the '{@link #getAt() <em>At</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAt()
   * @generated
   * @ordered
   */
  protected static final String AT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAt() <em>At</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAt()
   * @generated
   * @ordered
   */
  protected String at = AT_EDEFAULT;

  /**
   * The cached value of the '{@link #getTn() <em>Tn</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTn()
   * @generated
   * @ordered
   */
  protected TriggerName tn;

  /**
   * The cached value of the '{@link #getEvery() <em>Every</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEvery()
   * @generated
   * @ordered
   */
  protected EVERY every;

  /**
   * The cached value of the '{@link #getTv() <em>Tv</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTv()
   * @generated
   * @ordered
   */
  protected TimeValue tv;

  /**
   * The cached value of the '{@link #getSv() <em>Sv</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSv()
   * @generated
   * @ordered
   */
  protected StringValue sv;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DefinitionTriggerImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SiddhiPackage.eINSTANCE.getDefinitionTrigger();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getTrigger()
  {
    return trigger;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTrigger(String newTrigger)
  {
    String oldTrigger = trigger;
    trigger = newTrigger;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.DEFINITION_TRIGGER__TRIGGER, oldTrigger, trigger));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getAt()
  {
    return at;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAt(String newAt)
  {
    String oldAt = at;
    at = newAt;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.DEFINITION_TRIGGER__AT, oldAt, at));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TriggerName getTn()
  {
    return tn;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTn(TriggerName newTn, NotificationChain msgs)
  {
    TriggerName oldTn = tn;
    tn = newTn;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SiddhiPackage.DEFINITION_TRIGGER__TN, oldTn, newTn);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTn(TriggerName newTn)
  {
    if (newTn != tn)
    {
      NotificationChain msgs = null;
      if (tn != null)
        msgs = ((InternalEObject)tn).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.DEFINITION_TRIGGER__TN, null, msgs);
      if (newTn != null)
        msgs = ((InternalEObject)newTn).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.DEFINITION_TRIGGER__TN, null, msgs);
      msgs = basicSetTn(newTn, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.DEFINITION_TRIGGER__TN, newTn, newTn));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EVERY getEvery()
  {
    return every;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetEvery(EVERY newEvery, NotificationChain msgs)
  {
    EVERY oldEvery = every;
    every = newEvery;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SiddhiPackage.DEFINITION_TRIGGER__EVERY, oldEvery, newEvery);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setEvery(EVERY newEvery)
  {
    if (newEvery != every)
    {
      NotificationChain msgs = null;
      if (every != null)
        msgs = ((InternalEObject)every).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.DEFINITION_TRIGGER__EVERY, null, msgs);
      if (newEvery != null)
        msgs = ((InternalEObject)newEvery).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.DEFINITION_TRIGGER__EVERY, null, msgs);
      msgs = basicSetEvery(newEvery, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.DEFINITION_TRIGGER__EVERY, newEvery, newEvery));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TimeValue getTv()
  {
    return tv;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTv(TimeValue newTv, NotificationChain msgs)
  {
    TimeValue oldTv = tv;
    tv = newTv;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SiddhiPackage.DEFINITION_TRIGGER__TV, oldTv, newTv);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTv(TimeValue newTv)
  {
    if (newTv != tv)
    {
      NotificationChain msgs = null;
      if (tv != null)
        msgs = ((InternalEObject)tv).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.DEFINITION_TRIGGER__TV, null, msgs);
      if (newTv != null)
        msgs = ((InternalEObject)newTv).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.DEFINITION_TRIGGER__TV, null, msgs);
      msgs = basicSetTv(newTv, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.DEFINITION_TRIGGER__TV, newTv, newTv));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public StringValue getSv()
  {
    return sv;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSv(StringValue newSv, NotificationChain msgs)
  {
    StringValue oldSv = sv;
    sv = newSv;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SiddhiPackage.DEFINITION_TRIGGER__SV, oldSv, newSv);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSv(StringValue newSv)
  {
    if (newSv != sv)
    {
      NotificationChain msgs = null;
      if (sv != null)
        msgs = ((InternalEObject)sv).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.DEFINITION_TRIGGER__SV, null, msgs);
      if (newSv != null)
        msgs = ((InternalEObject)newSv).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.DEFINITION_TRIGGER__SV, null, msgs);
      msgs = basicSetSv(newSv, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.DEFINITION_TRIGGER__SV, newSv, newSv));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SiddhiPackage.DEFINITION_TRIGGER__TN:
        return basicSetTn(null, msgs);
      case SiddhiPackage.DEFINITION_TRIGGER__EVERY:
        return basicSetEvery(null, msgs);
      case SiddhiPackage.DEFINITION_TRIGGER__TV:
        return basicSetTv(null, msgs);
      case SiddhiPackage.DEFINITION_TRIGGER__SV:
        return basicSetSv(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SiddhiPackage.DEFINITION_TRIGGER__TRIGGER:
        return getTrigger();
      case SiddhiPackage.DEFINITION_TRIGGER__AT:
        return getAt();
      case SiddhiPackage.DEFINITION_TRIGGER__TN:
        return getTn();
      case SiddhiPackage.DEFINITION_TRIGGER__EVERY:
        return getEvery();
      case SiddhiPackage.DEFINITION_TRIGGER__TV:
        return getTv();
      case SiddhiPackage.DEFINITION_TRIGGER__SV:
        return getSv();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SiddhiPackage.DEFINITION_TRIGGER__TRIGGER:
        setTrigger((String)newValue);
        return;
      case SiddhiPackage.DEFINITION_TRIGGER__AT:
        setAt((String)newValue);
        return;
      case SiddhiPackage.DEFINITION_TRIGGER__TN:
        setTn((TriggerName)newValue);
        return;
      case SiddhiPackage.DEFINITION_TRIGGER__EVERY:
        setEvery((EVERY)newValue);
        return;
      case SiddhiPackage.DEFINITION_TRIGGER__TV:
        setTv((TimeValue)newValue);
        return;
      case SiddhiPackage.DEFINITION_TRIGGER__SV:
        setSv((StringValue)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SiddhiPackage.DEFINITION_TRIGGER__TRIGGER:
        setTrigger(TRIGGER_EDEFAULT);
        return;
      case SiddhiPackage.DEFINITION_TRIGGER__AT:
        setAt(AT_EDEFAULT);
        return;
      case SiddhiPackage.DEFINITION_TRIGGER__TN:
        setTn((TriggerName)null);
        return;
      case SiddhiPackage.DEFINITION_TRIGGER__EVERY:
        setEvery((EVERY)null);
        return;
      case SiddhiPackage.DEFINITION_TRIGGER__TV:
        setTv((TimeValue)null);
        return;
      case SiddhiPackage.DEFINITION_TRIGGER__SV:
        setSv((StringValue)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SiddhiPackage.DEFINITION_TRIGGER__TRIGGER:
        return TRIGGER_EDEFAULT == null ? trigger != null : !TRIGGER_EDEFAULT.equals(trigger);
      case SiddhiPackage.DEFINITION_TRIGGER__AT:
        return AT_EDEFAULT == null ? at != null : !AT_EDEFAULT.equals(at);
      case SiddhiPackage.DEFINITION_TRIGGER__TN:
        return tn != null;
      case SiddhiPackage.DEFINITION_TRIGGER__EVERY:
        return every != null;
      case SiddhiPackage.DEFINITION_TRIGGER__TV:
        return tv != null;
      case SiddhiPackage.DEFINITION_TRIGGER__SV:
        return sv != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int eBaseStructuralFeatureID(int derivedFeatureID, Class<?> baseClass)
  {
    if (baseClass == TRIGGER.class)
    {
      switch (derivedFeatureID)
      {
        case SiddhiPackage.DEFINITION_TRIGGER__TRIGGER: return SiddhiPackage.TRIGGER__TRIGGER;
        default: return -1;
      }
    }
    if (baseClass == AT.class)
    {
      switch (derivedFeatureID)
      {
        case SiddhiPackage.DEFINITION_TRIGGER__AT: return SiddhiPackage.AT__AT;
        default: return -1;
      }
    }
    return super.eBaseStructuralFeatureID(derivedFeatureID, baseClass);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int eDerivedStructuralFeatureID(int baseFeatureID, Class<?> baseClass)
  {
    if (baseClass == TRIGGER.class)
    {
      switch (baseFeatureID)
      {
        case SiddhiPackage.TRIGGER__TRIGGER: return SiddhiPackage.DEFINITION_TRIGGER__TRIGGER;
        default: return -1;
      }
    }
    if (baseClass == AT.class)
    {
      switch (baseFeatureID)
      {
        case SiddhiPackage.AT__AT: return SiddhiPackage.DEFINITION_TRIGGER__AT;
        default: return -1;
      }
    }
    return super.eDerivedStructuralFeatureID(baseFeatureID, baseClass);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (trigger: ");
    result.append(trigger);
    result.append(", at: ");
    result.append(at);
    result.append(')');
    return result.toString();
  }

} //DefinitionTriggerImpl
