/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.siddhi.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.siddhi.siddhi.Annotation;
import org.xtext.example.siddhi.siddhi.BEGIN;
import org.xtext.example.siddhi.siddhi.END;
import org.xtext.example.siddhi.siddhi.ExecPartition;
import org.xtext.example.siddhi.siddhi.PartitionWithStream;
import org.xtext.example.siddhi.siddhi.Query;
import org.xtext.example.siddhi.siddhi.SiddhiPackage;
import org.xtext.example.siddhi.siddhi.WITH;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Exec Partition</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.ExecPartitionImpl#getWi <em>Wi</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.ExecPartitionImpl#getBegin <em>Begin</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.ExecPartitionImpl#getEnd <em>End</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.ExecPartitionImpl#getAnn4 <em>Ann4</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.ExecPartitionImpl#getPartWithStream <em>Part With Stream</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.ExecPartitionImpl#getQu <em>Qu</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ExecPartitionImpl extends PARTITIONImpl implements ExecPartition
{
  /**
   * The default value of the '{@link #getWi() <em>Wi</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWi()
   * @generated
   * @ordered
   */
  protected static final String WI_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getWi() <em>Wi</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWi()
   * @generated
   * @ordered
   */
  protected String wi = WI_EDEFAULT;

  /**
   * The default value of the '{@link #getBegin() <em>Begin</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBegin()
   * @generated
   * @ordered
   */
  protected static final String BEGIN_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getBegin() <em>Begin</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBegin()
   * @generated
   * @ordered
   */
  protected String begin = BEGIN_EDEFAULT;

  /**
   * The default value of the '{@link #getEnd() <em>End</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnd()
   * @generated
   * @ordered
   */
  protected static final String END_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEnd() <em>End</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnd()
   * @generated
   * @ordered
   */
  protected String end = END_EDEFAULT;

  /**
   * The cached value of the '{@link #getAnn4() <em>Ann4</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAnn4()
   * @generated
   * @ordered
   */
  protected EList<Annotation> ann4;

  /**
   * The cached value of the '{@link #getPartWithStream() <em>Part With Stream</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPartWithStream()
   * @generated
   * @ordered
   */
  protected EList<PartitionWithStream> partWithStream;

  /**
   * The cached value of the '{@link #getQu() <em>Qu</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQu()
   * @generated
   * @ordered
   */
  protected EList<Query> qu;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExecPartitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SiddhiPackage.eINSTANCE.getExecPartition();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getWi()
  {
    return wi;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setWi(String newWi)
  {
    String oldWi = wi;
    wi = newWi;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.EXEC_PARTITION__WI, oldWi, wi));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getBegin()
  {
    return begin;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setBegin(String newBegin)
  {
    String oldBegin = begin;
    begin = newBegin;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.EXEC_PARTITION__BEGIN, oldBegin, begin));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getEnd()
  {
    return end;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setEnd(String newEnd)
  {
    String oldEnd = end;
    end = newEnd;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.EXEC_PARTITION__END, oldEnd, end));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Annotation> getAnn4()
  {
    if (ann4 == null)
    {
      ann4 = new EObjectContainmentEList<Annotation>(Annotation.class, this, SiddhiPackage.EXEC_PARTITION__ANN4);
    }
    return ann4;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<PartitionWithStream> getPartWithStream()
  {
    if (partWithStream == null)
    {
      partWithStream = new EObjectContainmentEList<PartitionWithStream>(PartitionWithStream.class, this, SiddhiPackage.EXEC_PARTITION__PART_WITH_STREAM);
    }
    return partWithStream;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Query> getQu()
  {
    if (qu == null)
    {
      qu = new EObjectContainmentEList<Query>(Query.class, this, SiddhiPackage.EXEC_PARTITION__QU);
    }
    return qu;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SiddhiPackage.EXEC_PARTITION__ANN4:
        return ((InternalEList<?>)getAnn4()).basicRemove(otherEnd, msgs);
      case SiddhiPackage.EXEC_PARTITION__PART_WITH_STREAM:
        return ((InternalEList<?>)getPartWithStream()).basicRemove(otherEnd, msgs);
      case SiddhiPackage.EXEC_PARTITION__QU:
        return ((InternalEList<?>)getQu()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SiddhiPackage.EXEC_PARTITION__WI:
        return getWi();
      case SiddhiPackage.EXEC_PARTITION__BEGIN:
        return getBegin();
      case SiddhiPackage.EXEC_PARTITION__END:
        return getEnd();
      case SiddhiPackage.EXEC_PARTITION__ANN4:
        return getAnn4();
      case SiddhiPackage.EXEC_PARTITION__PART_WITH_STREAM:
        return getPartWithStream();
      case SiddhiPackage.EXEC_PARTITION__QU:
        return getQu();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SiddhiPackage.EXEC_PARTITION__WI:
        setWi((String)newValue);
        return;
      case SiddhiPackage.EXEC_PARTITION__BEGIN:
        setBegin((String)newValue);
        return;
      case SiddhiPackage.EXEC_PARTITION__END:
        setEnd((String)newValue);
        return;
      case SiddhiPackage.EXEC_PARTITION__ANN4:
        getAnn4().clear();
        getAnn4().addAll((Collection<? extends Annotation>)newValue);
        return;
      case SiddhiPackage.EXEC_PARTITION__PART_WITH_STREAM:
        getPartWithStream().clear();
        getPartWithStream().addAll((Collection<? extends PartitionWithStream>)newValue);
        return;
      case SiddhiPackage.EXEC_PARTITION__QU:
        getQu().clear();
        getQu().addAll((Collection<? extends Query>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SiddhiPackage.EXEC_PARTITION__WI:
        setWi(WI_EDEFAULT);
        return;
      case SiddhiPackage.EXEC_PARTITION__BEGIN:
        setBegin(BEGIN_EDEFAULT);
        return;
      case SiddhiPackage.EXEC_PARTITION__END:
        setEnd(END_EDEFAULT);
        return;
      case SiddhiPackage.EXEC_PARTITION__ANN4:
        getAnn4().clear();
        return;
      case SiddhiPackage.EXEC_PARTITION__PART_WITH_STREAM:
        getPartWithStream().clear();
        return;
      case SiddhiPackage.EXEC_PARTITION__QU:
        getQu().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SiddhiPackage.EXEC_PARTITION__WI:
        return WI_EDEFAULT == null ? wi != null : !WI_EDEFAULT.equals(wi);
      case SiddhiPackage.EXEC_PARTITION__BEGIN:
        return BEGIN_EDEFAULT == null ? begin != null : !BEGIN_EDEFAULT.equals(begin);
      case SiddhiPackage.EXEC_PARTITION__END:
        return END_EDEFAULT == null ? end != null : !END_EDEFAULT.equals(end);
      case SiddhiPackage.EXEC_PARTITION__ANN4:
        return ann4 != null && !ann4.isEmpty();
      case SiddhiPackage.EXEC_PARTITION__PART_WITH_STREAM:
        return partWithStream != null && !partWithStream.isEmpty();
      case SiddhiPackage.EXEC_PARTITION__QU:
        return qu != null && !qu.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int eBaseStructuralFeatureID(int derivedFeatureID, Class<?> baseClass)
  {
    if (baseClass == WITH.class)
    {
      switch (derivedFeatureID)
      {
        case SiddhiPackage.EXEC_PARTITION__WI: return SiddhiPackage.WITH__WI;
        default: return -1;
      }
    }
    if (baseClass == BEGIN.class)
    {
      switch (derivedFeatureID)
      {
        case SiddhiPackage.EXEC_PARTITION__BEGIN: return SiddhiPackage.BEGIN__BEGIN;
        default: return -1;
      }
    }
    if (baseClass == END.class)
    {
      switch (derivedFeatureID)
      {
        case SiddhiPackage.EXEC_PARTITION__END: return SiddhiPackage.END__END;
        default: return -1;
      }
    }
    return super.eBaseStructuralFeatureID(derivedFeatureID, baseClass);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int eDerivedStructuralFeatureID(int baseFeatureID, Class<?> baseClass)
  {
    if (baseClass == WITH.class)
    {
      switch (baseFeatureID)
      {
        case SiddhiPackage.WITH__WI: return SiddhiPackage.EXEC_PARTITION__WI;
        default: return -1;
      }
    }
    if (baseClass == BEGIN.class)
    {
      switch (baseFeatureID)
      {
        case SiddhiPackage.BEGIN__BEGIN: return SiddhiPackage.EXEC_PARTITION__BEGIN;
        default: return -1;
      }
    }
    if (baseClass == END.class)
    {
      switch (baseFeatureID)
      {
        case SiddhiPackage.END__END: return SiddhiPackage.EXEC_PARTITION__END;
        default: return -1;
      }
    }
    return super.eDerivedStructuralFeatureID(baseFeatureID, baseClass);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (wi: ");
    result.append(wi);
    result.append(", begin: ");
    result.append(begin);
    result.append(", end: ");
    result.append(end);
    result.append(')');
    return result.toString();
  }

} //ExecPartitionImpl
