/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.siddhi.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.siddhi.siddhi.AttributeList;
import org.xtext.example.siddhi.siddhi.FunctionId;
import org.xtext.example.siddhi.siddhi.FunctionNamespace;
import org.xtext.example.siddhi.siddhi.FunctionOperation;
import org.xtext.example.siddhi.siddhi.SiddhiPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Function Operation</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.FunctionOperationImpl#getFuncNamespace <em>Func Namespace</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.FunctionOperationImpl#getFuncId <em>Func Id</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.FunctionOperationImpl#getAttrList <em>Attr List</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FunctionOperationImpl extends MinimalEObjectImpl.Container implements FunctionOperation
{
  /**
   * The cached value of the '{@link #getFuncNamespace() <em>Func Namespace</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFuncNamespace()
   * @generated
   * @ordered
   */
  protected FunctionNamespace funcNamespace;

  /**
   * The cached value of the '{@link #getFuncId() <em>Func Id</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFuncId()
   * @generated
   * @ordered
   */
  protected FunctionId funcId;

  /**
   * The cached value of the '{@link #getAttrList() <em>Attr List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAttrList()
   * @generated
   * @ordered
   */
  protected AttributeList attrList;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FunctionOperationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SiddhiPackage.eINSTANCE.getFunctionOperation();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FunctionNamespace getFuncNamespace()
  {
    return funcNamespace;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFuncNamespace(FunctionNamespace newFuncNamespace, NotificationChain msgs)
  {
    FunctionNamespace oldFuncNamespace = funcNamespace;
    funcNamespace = newFuncNamespace;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SiddhiPackage.FUNCTION_OPERATION__FUNC_NAMESPACE, oldFuncNamespace, newFuncNamespace);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFuncNamespace(FunctionNamespace newFuncNamespace)
  {
    if (newFuncNamespace != funcNamespace)
    {
      NotificationChain msgs = null;
      if (funcNamespace != null)
        msgs = ((InternalEObject)funcNamespace).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.FUNCTION_OPERATION__FUNC_NAMESPACE, null, msgs);
      if (newFuncNamespace != null)
        msgs = ((InternalEObject)newFuncNamespace).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.FUNCTION_OPERATION__FUNC_NAMESPACE, null, msgs);
      msgs = basicSetFuncNamespace(newFuncNamespace, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.FUNCTION_OPERATION__FUNC_NAMESPACE, newFuncNamespace, newFuncNamespace));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FunctionId getFuncId()
  {
    return funcId;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFuncId(FunctionId newFuncId, NotificationChain msgs)
  {
    FunctionId oldFuncId = funcId;
    funcId = newFuncId;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SiddhiPackage.FUNCTION_OPERATION__FUNC_ID, oldFuncId, newFuncId);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFuncId(FunctionId newFuncId)
  {
    if (newFuncId != funcId)
    {
      NotificationChain msgs = null;
      if (funcId != null)
        msgs = ((InternalEObject)funcId).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.FUNCTION_OPERATION__FUNC_ID, null, msgs);
      if (newFuncId != null)
        msgs = ((InternalEObject)newFuncId).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.FUNCTION_OPERATION__FUNC_ID, null, msgs);
      msgs = basicSetFuncId(newFuncId, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.FUNCTION_OPERATION__FUNC_ID, newFuncId, newFuncId));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AttributeList getAttrList()
  {
    return attrList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAttrList(AttributeList newAttrList, NotificationChain msgs)
  {
    AttributeList oldAttrList = attrList;
    attrList = newAttrList;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SiddhiPackage.FUNCTION_OPERATION__ATTR_LIST, oldAttrList, newAttrList);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAttrList(AttributeList newAttrList)
  {
    if (newAttrList != attrList)
    {
      NotificationChain msgs = null;
      if (attrList != null)
        msgs = ((InternalEObject)attrList).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.FUNCTION_OPERATION__ATTR_LIST, null, msgs);
      if (newAttrList != null)
        msgs = ((InternalEObject)newAttrList).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.FUNCTION_OPERATION__ATTR_LIST, null, msgs);
      msgs = basicSetAttrList(newAttrList, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.FUNCTION_OPERATION__ATTR_LIST, newAttrList, newAttrList));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SiddhiPackage.FUNCTION_OPERATION__FUNC_NAMESPACE:
        return basicSetFuncNamespace(null, msgs);
      case SiddhiPackage.FUNCTION_OPERATION__FUNC_ID:
        return basicSetFuncId(null, msgs);
      case SiddhiPackage.FUNCTION_OPERATION__ATTR_LIST:
        return basicSetAttrList(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SiddhiPackage.FUNCTION_OPERATION__FUNC_NAMESPACE:
        return getFuncNamespace();
      case SiddhiPackage.FUNCTION_OPERATION__FUNC_ID:
        return getFuncId();
      case SiddhiPackage.FUNCTION_OPERATION__ATTR_LIST:
        return getAttrList();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SiddhiPackage.FUNCTION_OPERATION__FUNC_NAMESPACE:
        setFuncNamespace((FunctionNamespace)newValue);
        return;
      case SiddhiPackage.FUNCTION_OPERATION__FUNC_ID:
        setFuncId((FunctionId)newValue);
        return;
      case SiddhiPackage.FUNCTION_OPERATION__ATTR_LIST:
        setAttrList((AttributeList)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SiddhiPackage.FUNCTION_OPERATION__FUNC_NAMESPACE:
        setFuncNamespace((FunctionNamespace)null);
        return;
      case SiddhiPackage.FUNCTION_OPERATION__FUNC_ID:
        setFuncId((FunctionId)null);
        return;
      case SiddhiPackage.FUNCTION_OPERATION__ATTR_LIST:
        setAttrList((AttributeList)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SiddhiPackage.FUNCTION_OPERATION__FUNC_NAMESPACE:
        return funcNamespace != null;
      case SiddhiPackage.FUNCTION_OPERATION__FUNC_ID:
        return funcId != null;
      case SiddhiPackage.FUNCTION_OPERATION__ATTR_LIST:
        return attrList != null;
    }
    return super.eIsSet(featureID);
  }

} //FunctionOperationImpl
