/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.siddhi.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.siddhi.siddhi.AttributeReference;
import org.xtext.example.siddhi.siddhi.OutAttr;
import org.xtext.example.siddhi.siddhi.OutputAttribute;
import org.xtext.example.siddhi.siddhi.SiddhiPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Output Attribute</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.OutputAttributeImpl#getOutAttr <em>Out Attr</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.OutputAttributeImpl#getAttr_ref <em>Attr ref</em>}</li>
 * </ul>
 *
 * @generated
 */
public class OutputAttributeImpl extends MinimalEObjectImpl.Container implements OutputAttribute
{
  /**
   * The cached value of the '{@link #getOutAttr() <em>Out Attr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOutAttr()
   * @generated
   * @ordered
   */
  protected OutAttr outAttr;

  /**
   * The cached value of the '{@link #getAttr_ref() <em>Attr ref</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAttr_ref()
   * @generated
   * @ordered
   */
  protected AttributeReference attr_ref;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OutputAttributeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SiddhiPackage.eINSTANCE.getOutputAttribute();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public OutAttr getOutAttr()
  {
    return outAttr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetOutAttr(OutAttr newOutAttr, NotificationChain msgs)
  {
    OutAttr oldOutAttr = outAttr;
    outAttr = newOutAttr;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SiddhiPackage.OUTPUT_ATTRIBUTE__OUT_ATTR, oldOutAttr, newOutAttr);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setOutAttr(OutAttr newOutAttr)
  {
    if (newOutAttr != outAttr)
    {
      NotificationChain msgs = null;
      if (outAttr != null)
        msgs = ((InternalEObject)outAttr).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.OUTPUT_ATTRIBUTE__OUT_ATTR, null, msgs);
      if (newOutAttr != null)
        msgs = ((InternalEObject)newOutAttr).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.OUTPUT_ATTRIBUTE__OUT_ATTR, null, msgs);
      msgs = basicSetOutAttr(newOutAttr, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.OUTPUT_ATTRIBUTE__OUT_ATTR, newOutAttr, newOutAttr));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AttributeReference getAttr_ref()
  {
    return attr_ref;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAttr_ref(AttributeReference newAttr_ref, NotificationChain msgs)
  {
    AttributeReference oldAttr_ref = attr_ref;
    attr_ref = newAttr_ref;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SiddhiPackage.OUTPUT_ATTRIBUTE__ATTR_REF, oldAttr_ref, newAttr_ref);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAttr_ref(AttributeReference newAttr_ref)
  {
    if (newAttr_ref != attr_ref)
    {
      NotificationChain msgs = null;
      if (attr_ref != null)
        msgs = ((InternalEObject)attr_ref).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.OUTPUT_ATTRIBUTE__ATTR_REF, null, msgs);
      if (newAttr_ref != null)
        msgs = ((InternalEObject)newAttr_ref).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.OUTPUT_ATTRIBUTE__ATTR_REF, null, msgs);
      msgs = basicSetAttr_ref(newAttr_ref, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.OUTPUT_ATTRIBUTE__ATTR_REF, newAttr_ref, newAttr_ref));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SiddhiPackage.OUTPUT_ATTRIBUTE__OUT_ATTR:
        return basicSetOutAttr(null, msgs);
      case SiddhiPackage.OUTPUT_ATTRIBUTE__ATTR_REF:
        return basicSetAttr_ref(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SiddhiPackage.OUTPUT_ATTRIBUTE__OUT_ATTR:
        return getOutAttr();
      case SiddhiPackage.OUTPUT_ATTRIBUTE__ATTR_REF:
        return getAttr_ref();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SiddhiPackage.OUTPUT_ATTRIBUTE__OUT_ATTR:
        setOutAttr((OutAttr)newValue);
        return;
      case SiddhiPackage.OUTPUT_ATTRIBUTE__ATTR_REF:
        setAttr_ref((AttributeReference)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SiddhiPackage.OUTPUT_ATTRIBUTE__OUT_ATTR:
        setOutAttr((OutAttr)null);
        return;
      case SiddhiPackage.OUTPUT_ATTRIBUTE__ATTR_REF:
        setAttr_ref((AttributeReference)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SiddhiPackage.OUTPUT_ATTRIBUTE__OUT_ATTR:
        return outAttr != null;
      case SiddhiPackage.OUTPUT_ATTRIBUTE__ATTR_REF:
        return attr_ref != null;
    }
    return super.eIsSet(featureID);
  }

} //OutputAttributeImpl
