/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.siddhi.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.siddhi.siddhi.LogicalAbsentStatefulSource;
import org.xtext.example.siddhi.siddhi.LogicalStatefulSource;
import org.xtext.example.siddhi.siddhi.PatternCollectionStatefulSource;
import org.xtext.example.siddhi.siddhi.PatternSource;
import org.xtext.example.siddhi.siddhi.SiddhiPackage;
import org.xtext.example.siddhi.siddhi.StandardStatefulSource;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Pattern Source</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.PatternSourceImpl#getLss <em>Lss</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.PatternSourceImpl#getPss <em>Pss</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.PatternSourceImpl#getStdss <em>Stdss</em>}</li>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.PatternSourceImpl#getLogicalAbsStatefulSrc <em>Logical Abs Stateful Src</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PatternSourceImpl extends MinimalEObjectImpl.Container implements PatternSource
{
  /**
   * The cached value of the '{@link #getLss() <em>Lss</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLss()
   * @generated
   * @ordered
   */
  protected LogicalStatefulSource lss;

  /**
   * The cached value of the '{@link #getPss() <em>Pss</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPss()
   * @generated
   * @ordered
   */
  protected PatternCollectionStatefulSource pss;

  /**
   * The cached value of the '{@link #getStdss() <em>Stdss</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStdss()
   * @generated
   * @ordered
   */
  protected StandardStatefulSource stdss;

  /**
   * The cached value of the '{@link #getLogicalAbsStatefulSrc() <em>Logical Abs Stateful Src</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLogicalAbsStatefulSrc()
   * @generated
   * @ordered
   */
  protected LogicalAbsentStatefulSource logicalAbsStatefulSrc;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PatternSourceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SiddhiPackage.eINSTANCE.getPatternSource();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LogicalStatefulSource getLss()
  {
    return lss;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLss(LogicalStatefulSource newLss, NotificationChain msgs)
  {
    LogicalStatefulSource oldLss = lss;
    lss = newLss;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SiddhiPackage.PATTERN_SOURCE__LSS, oldLss, newLss);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLss(LogicalStatefulSource newLss)
  {
    if (newLss != lss)
    {
      NotificationChain msgs = null;
      if (lss != null)
        msgs = ((InternalEObject)lss).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.PATTERN_SOURCE__LSS, null, msgs);
      if (newLss != null)
        msgs = ((InternalEObject)newLss).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.PATTERN_SOURCE__LSS, null, msgs);
      msgs = basicSetLss(newLss, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.PATTERN_SOURCE__LSS, newLss, newLss));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PatternCollectionStatefulSource getPss()
  {
    return pss;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPss(PatternCollectionStatefulSource newPss, NotificationChain msgs)
  {
    PatternCollectionStatefulSource oldPss = pss;
    pss = newPss;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SiddhiPackage.PATTERN_SOURCE__PSS, oldPss, newPss);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPss(PatternCollectionStatefulSource newPss)
  {
    if (newPss != pss)
    {
      NotificationChain msgs = null;
      if (pss != null)
        msgs = ((InternalEObject)pss).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.PATTERN_SOURCE__PSS, null, msgs);
      if (newPss != null)
        msgs = ((InternalEObject)newPss).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.PATTERN_SOURCE__PSS, null, msgs);
      msgs = basicSetPss(newPss, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.PATTERN_SOURCE__PSS, newPss, newPss));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public StandardStatefulSource getStdss()
  {
    return stdss;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetStdss(StandardStatefulSource newStdss, NotificationChain msgs)
  {
    StandardStatefulSource oldStdss = stdss;
    stdss = newStdss;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SiddhiPackage.PATTERN_SOURCE__STDSS, oldStdss, newStdss);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setStdss(StandardStatefulSource newStdss)
  {
    if (newStdss != stdss)
    {
      NotificationChain msgs = null;
      if (stdss != null)
        msgs = ((InternalEObject)stdss).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.PATTERN_SOURCE__STDSS, null, msgs);
      if (newStdss != null)
        msgs = ((InternalEObject)newStdss).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.PATTERN_SOURCE__STDSS, null, msgs);
      msgs = basicSetStdss(newStdss, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.PATTERN_SOURCE__STDSS, newStdss, newStdss));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LogicalAbsentStatefulSource getLogicalAbsStatefulSrc()
  {
    return logicalAbsStatefulSrc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLogicalAbsStatefulSrc(LogicalAbsentStatefulSource newLogicalAbsStatefulSrc, NotificationChain msgs)
  {
    LogicalAbsentStatefulSource oldLogicalAbsStatefulSrc = logicalAbsStatefulSrc;
    logicalAbsStatefulSrc = newLogicalAbsStatefulSrc;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SiddhiPackage.PATTERN_SOURCE__LOGICAL_ABS_STATEFUL_SRC, oldLogicalAbsStatefulSrc, newLogicalAbsStatefulSrc);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLogicalAbsStatefulSrc(LogicalAbsentStatefulSource newLogicalAbsStatefulSrc)
  {
    if (newLogicalAbsStatefulSrc != logicalAbsStatefulSrc)
    {
      NotificationChain msgs = null;
      if (logicalAbsStatefulSrc != null)
        msgs = ((InternalEObject)logicalAbsStatefulSrc).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.PATTERN_SOURCE__LOGICAL_ABS_STATEFUL_SRC, null, msgs);
      if (newLogicalAbsStatefulSrc != null)
        msgs = ((InternalEObject)newLogicalAbsStatefulSrc).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SiddhiPackage.PATTERN_SOURCE__LOGICAL_ABS_STATEFUL_SRC, null, msgs);
      msgs = basicSetLogicalAbsStatefulSrc(newLogicalAbsStatefulSrc, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.PATTERN_SOURCE__LOGICAL_ABS_STATEFUL_SRC, newLogicalAbsStatefulSrc, newLogicalAbsStatefulSrc));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SiddhiPackage.PATTERN_SOURCE__LSS:
        return basicSetLss(null, msgs);
      case SiddhiPackage.PATTERN_SOURCE__PSS:
        return basicSetPss(null, msgs);
      case SiddhiPackage.PATTERN_SOURCE__STDSS:
        return basicSetStdss(null, msgs);
      case SiddhiPackage.PATTERN_SOURCE__LOGICAL_ABS_STATEFUL_SRC:
        return basicSetLogicalAbsStatefulSrc(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SiddhiPackage.PATTERN_SOURCE__LSS:
        return getLss();
      case SiddhiPackage.PATTERN_SOURCE__PSS:
        return getPss();
      case SiddhiPackage.PATTERN_SOURCE__STDSS:
        return getStdss();
      case SiddhiPackage.PATTERN_SOURCE__LOGICAL_ABS_STATEFUL_SRC:
        return getLogicalAbsStatefulSrc();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SiddhiPackage.PATTERN_SOURCE__LSS:
        setLss((LogicalStatefulSource)newValue);
        return;
      case SiddhiPackage.PATTERN_SOURCE__PSS:
        setPss((PatternCollectionStatefulSource)newValue);
        return;
      case SiddhiPackage.PATTERN_SOURCE__STDSS:
        setStdss((StandardStatefulSource)newValue);
        return;
      case SiddhiPackage.PATTERN_SOURCE__LOGICAL_ABS_STATEFUL_SRC:
        setLogicalAbsStatefulSrc((LogicalAbsentStatefulSource)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SiddhiPackage.PATTERN_SOURCE__LSS:
        setLss((LogicalStatefulSource)null);
        return;
      case SiddhiPackage.PATTERN_SOURCE__PSS:
        setPss((PatternCollectionStatefulSource)null);
        return;
      case SiddhiPackage.PATTERN_SOURCE__STDSS:
        setStdss((StandardStatefulSource)null);
        return;
      case SiddhiPackage.PATTERN_SOURCE__LOGICAL_ABS_STATEFUL_SRC:
        setLogicalAbsStatefulSrc((LogicalAbsentStatefulSource)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SiddhiPackage.PATTERN_SOURCE__LSS:
        return lss != null;
      case SiddhiPackage.PATTERN_SOURCE__PSS:
        return pss != null;
      case SiddhiPackage.PATTERN_SOURCE__STDSS:
        return stdss != null;
      case SiddhiPackage.PATTERN_SOURCE__LOGICAL_ABS_STATEFUL_SRC:
        return logicalAbsStatefulSrc != null;
    }
    return super.eIsSet(featureID);
  }

} //PatternSourceImpl
