/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.siddhi.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.siddhi.siddhi.SequenceCollectionStatefulSource;
import org.xtext.example.siddhi.siddhi.SiddhiPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Sequence Collection Stateful Source</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SequenceCollectionStatefulSourceImpl extends SequenceSourceImpl implements SequenceCollectionStatefulSource
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SequenceCollectionStatefulSourceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SiddhiPackage.eINSTANCE.getSequenceCollectionStatefulSource();
  }

} //SequenceCollectionStatefulSourceImpl
