/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.siddhi.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.siddhi.siddhi.SiddhiPackage;
import org.xtext.example.siddhi.siddhi.UNIDIRECTIONAL;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>UNIDIRECTIONAL</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.siddhi.siddhi.impl.UNIDIRECTIONALImpl#getUnidirectional <em>Unidirectional</em>}</li>
 * </ul>
 *
 * @generated
 */
public class UNIDIRECTIONALImpl extends MinimalEObjectImpl.Container implements UNIDIRECTIONAL
{
  /**
   * The default value of the '{@link #getUnidirectional() <em>Unidirectional</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUnidirectional()
   * @generated
   * @ordered
   */
  protected static final String UNIDIRECTIONAL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getUnidirectional() <em>Unidirectional</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUnidirectional()
   * @generated
   * @ordered
   */
  protected String unidirectional = UNIDIRECTIONAL_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UNIDIRECTIONALImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SiddhiPackage.eINSTANCE.getUNIDIRECTIONAL();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getUnidirectional()
  {
    return unidirectional;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setUnidirectional(String newUnidirectional)
  {
    String oldUnidirectional = unidirectional;
    unidirectional = newUnidirectional;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SiddhiPackage.UNIDIRECTIONAL__UNIDIRECTIONAL, oldUnidirectional, unidirectional));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SiddhiPackage.UNIDIRECTIONAL__UNIDIRECTIONAL:
        return getUnidirectional();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SiddhiPackage.UNIDIRECTIONAL__UNIDIRECTIONAL:
        setUnidirectional((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SiddhiPackage.UNIDIRECTIONAL__UNIDIRECTIONAL:
        setUnidirectional(UNIDIRECTIONAL_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SiddhiPackage.UNIDIRECTIONAL__UNIDIRECTIONAL:
        return UNIDIRECTIONAL_EDEFAULT == null ? unidirectional != null : !UNIDIRECTIONAL_EDEFAULT.equals(unidirectional);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (unidirectional: ");
    result.append(unidirectional);
    result.append(')');
    return result.toString();
  }

} //UNIDIRECTIONALImpl
