/*
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractSiddhiValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.xtext.example.siddhi.siddhi.SiddhiPackage.eINSTANCE);
		return result;
	}
	
}
