/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.siddhi.validation;

import org.xtext.example.siddhi.validation.AbstractSiddhiValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SiddhiValidator extends AbstractSiddhiValidator {
}
